import type { DriverModule } from "@/types";

/**
 * Yard-test (K53) modules for motorcycle (A1/A) and heavy (10/14) learners.
 * Original wording derived from official SA practical-test material. Procedural
 * figures (distances, speed bands) should be confirmed against the current
 * printed K53 manual before being treated as exam-certain.
 */
export const MOTORCYCLE_MODULES: DriverModule[] = [
  {
    id: "moto_inspection",
    name: "Pre-ride inspection",
    summary: "The checks to point out before the motorcycle test begins.",
    difficulty: 1,
    estMinutes: 6,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Tyres & wheels", instruction: "Check both tyres for tread, pressure, cuts and bulges, and that the wheels and spokes look sound.", tip: "Two small contact patches carry everything — tyre condition matters even more than on a car." },
      { n: 2, title: "Brakes", instruction: "Squeeze the front lever and press the rear pedal to confirm both brakes feel firm and the bike is held.", tip: "Spongy or loose brakes are an immediate concern — both must work independently." },
      { n: 3, title: "Chain & controls", instruction: "Check chain tension/lubrication, and that the throttle snaps back, the clutch and levers move freely, and the steering is not stiff.", tip: "A sticky throttle that doesn't return to idle is dangerous." },
      { n: 4, title: "Lights & signals", instruction: "Confirm the headlight (dipped/main), brake light, indicators and hooter all work.", tip: "Use a wall or window reflection to verify the rear light and brake light." },
      { n: 5, title: "Gear & fluids", instruction: "Check oil/fuel levels and that the mirrors are set; confirm the engine cut-off switch is in the run position.", tip: "Riders often forget the kill switch is off after a previous demo." },
    ],
    commonFaults: [
      "Missing a defect you were meant to point out",
      "Not checking both brakes independently",
      "Overlooking the throttle returning to idle on its own",
    ],
  },
  {
    id: "moto_moving_off",
    name: "Moving off & balance",
    summary: "Pull away smoothly and under full control, with the correct observation.",
    difficulty: 1,
    estMinutes: 6,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Prepare", instruction: "With the engine running, pull in the clutch, select first gear and keep both feet ready.", tip: "Cover the rear brake so you can steady the bike at walking pace." },
      { n: 2, title: "Observe", instruction: "Check mirrors and take a 'lifesaver' glance over your shoulder to cover the blind spot before moving.", tip: "On a motorcycle the shoulder glance is essential — mirrors alone leave a big blind spot." },
      { n: 3, title: "Feed the clutch", instruction: "Ease the clutch out to the friction point while gently opening the throttle to move off without stalling.", tip: "Find the bite gradually — snapping the clutch will jerk or stall the bike." },
      { n: 4, title: "Balance & feet up", instruction: "As the bike gathers pace, bring both feet onto the pegs and keep your eyes up and well ahead.", tip: "Looking far ahead steadies your balance; looking down makes you wobble." },
      { n: 5, title: "Settle", instruction: "Take up your road position toward the left, hold a steady speed and keep scanning.", tip: "Smooth, controlled balance at low speed is exactly what examiners reward." },
    ],
    commonFaults: [
      "Moving off without the shoulder (lifesaver) glance",
      "Stalling by releasing the clutch too quickly",
      "Looking down at the controls instead of ahead",
    ],
  },
  {
    id: "moto_slow_ride",
    name: "Slow ride & figure-of-eight",
    summary: "Hold a steady speed band through a slow, curved course without touching the lines or putting a foot down.",
    difficulty: 3,
    estMinutes: 12,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Set the controls", instruction: "Ride at low speed using clutch slip, a steady throttle and a trailing rear brake to keep the bike stable.", tip: "The clutch–throttle–rear-brake balance is what keeps a bike upright at crawling speed." },
      { n: 2, title: "Look through the curve", instruction: "Turn your head and look to where you want to go — to the exit of the curve — not at the front wheel.", tip: "The bike follows your eyes; fixing on the line you fear makes you ride onto it." },
      { n: 3, title: "Stay in the speed band", instruction: "Keep within the marked minimum and maximum speed — neither so slow you wobble nor so fast you run wide.", tip: "Too slow loses balance; too fast touches the outer line. Both are penalised." },
      { n: 4, title: "Figure-of-eight", instruction: "Flow smoothly from one circle into the other, shifting your balance and gaze as the direction changes.", tip: "Keep the bike moving — pausing or dabbing a foot down costs marks." },
      { n: 5, title: "Finish controlled", instruction: "Complete the course inside the boundaries and bring the bike to a steady, balanced stop where directed.", tip: "Never put a foot down mid-course unless you're about to fall." },
    ],
    commonFaults: [
      "Touching or crossing a boundary line",
      "Putting a foot down to balance",
      "Riding faster than the speed band to stay upright",
    ],
  },
  {
    id: "moto_incline_start",
    name: "Incline start (no roll-back)",
    summary: "Stop on a slope and move off without the motorcycle rolling backward.",
    difficulty: 3,
    estMinutes: 8,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Hold on the slope", instruction: "Stop on the incline holding the bike stationary with the rear brake (pedal), clutch in and first gear selected.", tip: "The rear brake holds the bike while your hands manage clutch and throttle." },
      { n: 2, title: "Build drive", instruction: "Open the throttle a little more than on the flat and bring the clutch to the friction point.", tip: "You need extra drive to overcome the slope — find the bite before releasing the brake." },
      { n: 3, title: "Release the brake", instruction: "Once you feel drive taking up, smoothly release the rear brake so the bike moves forward, not back.", tip: "If the bike dips back, you released too early — re-apply the rear brake and rebalance." },
      { n: 4, title: "Move off", instruction: "Ease the clutch fully out as you feed in throttle, bring your feet up and ride away under control.", tip: "Any backward roll is penalised, so err toward a touch more drive." },
    ],
    commonFaults: [
      "Rolling backward as you release the brake",
      "Stalling by letting the clutch out too fast",
      "Using only the front brake to hold on the slope",
    ],
  },
  {
    id: "moto_emergency_stop",
    name: "Emergency stop",
    summary: "Stop as quickly and safely as possible, in a straight line, using both brakes.",
    difficulty: 3,
    estMinutes: 6,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Approach", instruction: "Ride in at the set speed, upright and straight, with the bike balanced and your eyes up.", tip: "The stop must be straight-line — don't be leaning or turning when you brake." },
      { n: 2, title: "Both brakes together", instruction: "On the signal, apply the front brake firmly and progressively while also using the rear, squeezing — not grabbing.", tip: "The front brake does most of the work, but grabbing it can lock the front and drop the bike." },
      { n: 3, title: "Pull the clutch", instruction: "As you slow, pull in the clutch to prevent stalling and keep the bike stable to a complete stop.", tip: "Keep the wheels rolling — a locked wheel lengthens the stop and risks a slide." },
      { n: 4, title: "Stabilise", instruction: "Come to a full stop within the marked distance, put a foot (or feet) down and hold the bike steady.", tip: "A skid, a wobble or stopping past the line all cost you here." },
    ],
    commonFaults: [
      "Grabbing the front brake and locking the front wheel",
      "Using only one brake",
      "Skidding or stopping outside the marked distance",
    ],
  },
  {
    id: "moto_uturn",
    name: "U-turn (within the lines)",
    summary: "Turn the motorcycle around inside a marked width without touching a line or putting a foot down.",
    difficulty: 3,
    estMinutes: 8,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Set up wide", instruction: "Position the bike to the far side of the marked area so you use every centimetre of turning width available.", tip: "The turn is won before it starts — a tight entry line makes the arc impossible." },
      { n: 2, title: "Observe first", instruction: "Check mirrors and take a lifesaver glance over the shoulder you're turning toward before committing.", tip: "In the yard it proves your habit; on the road it saves your life." },
      { n: 3, title: "Head right around", instruction: "Turn your head and look all the way through the turn to where you want to finish — not at the front wheel or the lines.", tip: "Your tightest possible turn only happens when your chin is almost over your shoulder." },
      { n: 4, title: "Balance the controls", instruction: "Carry gentle drive with clutch slip and a trailing rear brake; keep the throttle steady rather than chopping it.", tip: "Closing the throttle mid-turn makes the bike drop into the turn — steady drive holds it up." },
      { n: 5, title: "Finish upright", instruction: "Complete the arc inside the boundaries, straighten up smoothly and ride out without a wobble.", tip: "A foot down or a line touched are the two classic score-killers here." },
    ],
    commonFaults: [
      "Entering too close to the turn side and running out of width",
      "Looking at the boundary line instead of through the turn",
      "Chopping the throttle and having to dab a foot down",
    ],
  },
  {
    id: "moto_lane_change",
    name: "Lane change (observation sequence)",
    summary: "The full mirrors–signal–lifesaver sequence for changing lanes on a motorcycle.",
    difficulty: 2,
    estMinutes: 7,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Mirrors", instruction: "Check your rear-view mirrors early, while there's still time to abort the plan calmly.", tip: "Bike mirrors show less than car mirrors — treat them as the start of the check, never the whole check." },
      { n: 2, title: "Signal", instruction: "Indicate clearly and early enough for riders and drivers behind to react.", tip: "Most bikes don't self-cancel — plan now to cancel the indicator afterwards." },
      { n: 3, title: "Lifesaver", instruction: "Just before moving, turn your head and check the blind spot on the side you're moving toward.", tip: "This glance is the single most examined habit in the motorcycle test — and the one that saves riders." },
      { n: 4, title: "Move smoothly", instruction: "Change lanes on a gentle diagonal, holding your speed steady so following traffic can predict you.", tip: "A slow drift, not a dart — sudden sideways movement is what car drivers fail to see." },
      { n: 5, title: "Cancel & re-position", instruction: "Cancel the indicator and settle into the dominant (safe) position in the new lane.", tip: "A blinking indicator left on tells traffic you're about to do something you're not." },
    ],
    commonFaults: [
      "Skipping the lifesaver glance",
      "Leaving the indicator flashing after the change",
      "Drifting into the new lane while still checking",
    ],
  },
  {
    id: "moto_road_ride",
    name: "Road ride: the observation system",
    summary: "The riding rhythm the examiner scores on the road: scan, mirrors, position, space.",
    difficulty: 2,
    estMinutes: 10,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Ride the scan cycle", instruction: "Keep your eyes moving: far ahead, middle distance, mirrors — roughly every five to eight seconds.", tip: "The examiner can see your helmet move; a frozen head reads as a frozen scan." },
      { n: 2, title: "Own your lane position", instruction: "Ride in the dominant position (around the right wheel-track of your lane) where drivers can see you, moving within the lane for hazards.", tip: "Hugging the gutter invites cars to share your lane; the dominant position claims it politely." },
      { n: 3, title: "Manage your space", instruction: "Keep a following distance of at least three seconds and open it in wind, rain or heavy traffic.", tip: "A bike can out-brake most cars — but the car behind you can't; leave escape space." },
      { n: 4, title: "Signal every intention", instruction: "Use indicators for every turn, lane change and pull-off, checked with a lifesaver each time — then cancel.", tip: "Sequence beats speed: mirrors, signal, lifesaver, act, cancel. Every single time." },
      { n: 5, title: "Cover the controls", instruction: "In town, ride with fingers resting over the front brake lever and toe near the rear brake.", tip: "Covering the brake removes half a second of reaction time — several metres at 60 km/h." },
    ],
    commonFaults: [
      "Staring at the vehicle ahead instead of scanning",
      "Riding in the gutter position through intersections",
      "Signalling correctly but forgetting to cancel afterwards",
    ],
  },
  {
    id: "moto_stop_park",
    name: "Stopping & parking the bike",
    summary: "End every ride the way the test ends: controlled stop, secure park, stand and dismount.",
    difficulty: 1,
    estMinutes: 6,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Plan the stop", instruction: "Check mirrors, signal left, and brake smoothly with both brakes while the bike is upright and straight.", tip: "Finish braking before walking pace; grabbing at the end topples slow bikes." },
      { n: 2, title: "Stop balanced", instruction: "Come to rest with the left foot down first, right foot on the rear brake, bars straight.", tip: "Left foot down keeps your right foot on the brake — the stable, examined habit." },
      { n: 3, title: "Secure the machine", instruction: "Select first gear (or neutral per instruction), kill the engine, and hold the front brake while dismounting.", tip: "First gear is your parking brake — bikes have no handbrake to save a roll-away." },
      { n: 4, title: "Deploy the stand", instruction: "Swing the side stand fully out (or heave onto the centre stand) and lean the bike onto it deliberately, on firm ground.", tip: "Soft tar on a hot day swallows side stands — a flat stone under the foot saves a dropped bike." },
      { n: 5, title: "Final check", instruction: "Bars to the left where fitted with a steering lock, and glance back at the bike as you walk away.", tip: "The walk-away glance catches the indicator you forgot and the stand that isn't fully out." },
    ],
    commonFaults: [
      "Stopping with the right foot down and no brake applied",
      "Parking in neutral on a slope",
      "Side stand not fully extended before leaning the bike",
    ],
  },
  {
    id: "moto_swerve",
    name: "Emergency swerve",
    summary: "Steer around a sudden obstacle at speed, then bring the bike to a controlled stop.",
    difficulty: 3,
    estMinutes: 7,
    group: "motorcycle",
    steps: [
      { n: 1, title: "Approach steady", instruction: "Ride in at the set approach speed, upright, relaxed and looking well ahead — not at the obstacle.", tip: "Tension on the bars makes the bike harder to steer; stay loose." },
      { n: 2, title: "Counter-steer around", instruction: "Press the handlebar on the side you want to go to, swerving smoothly around the obstacle.", tip: "Look at the gap you're aiming for, not the thing you're avoiding (target fixation)." },
      { n: 3, title: "Don't brake in the swerve", instruction: "Steer first; avoid braking while the bike is leaned over in the swerve, which can wash out the tyres.", tip: "Braking and hard steering at the same time overloads the available grip." },
      { n: 4, title: "Straighten & stop", instruction: "Once clear and upright again, apply both brakes progressively and bring the bike to a controlled stop.", tip: "Separate the actions: swerve, get upright, then brake." },
    ],
    commonFaults: [
      "Braking mid-swerve and losing grip",
      "Fixating on the obstacle instead of the escape path",
      "Stiffening up and steering too late",
    ],
  },
];

export const HEAVY_MODULES: DriverModule[] = [
  {
    id: "hv_inspection",
    name: "Pre-trip inspection",
    summary: "The heavy-vehicle walk-around and cab checks before driving.",
    difficulty: 2,
    estMinutes: 9,
    group: "heavy",
    steps: [
      { n: 1, title: "Walk-around", instruction: "Check tyres (including inners on twin axles), wheel nuts, bodywork, lights and that nothing is leaking underneath.", tip: "On multi-axle vehicles, don't forget the inner tyres you can't see at a glance." },
      { n: 2, title: "Drain the air tanks", instruction: "Drain any water/moisture from the air tanks and check there are no obvious air leaks.", tip: "Water left in the tanks can corrode the system or freeze valves in the cold." },
      { n: 3, title: "Build & test air pressure", instruction: "Start the engine and let air pressure build into the safe operating range before doing anything else.", tip: "The vehicle must not be moved until the gauges read in range and the low-pressure warning clears." },
      { n: 4, title: "Brake & light checks", instruction: "Test the service brake and parking (spring) brake, and confirm all lights, indicators and the hooter work.", tip: "The spring brake should hold the vehicle firmly on its own." },
      { n: 5, title: "Cab & coupling", instruction: "Confirm the tilt-cab is locked, mirrors are set, and (if articulated) the coupling and trailer connections are secure.", tip: "An unlocked tilt-cab or coupling is a serious defect to catch here." },
    ],
    commonFaults: [
      "Moving off before air pressure is in range",
      "Skipping the air-tank water drain",
      "Missing inner tyres or a loose wheel nut",
    ],
  },
  {
    id: "hv_air_brake_check",
    name: "Air-brake system check",
    summary: "Confirm the air-brake system builds, holds and warns correctly before driving.",
    difficulty: 3,
    estMinutes: 8,
    group: "heavy",
    steps: [
      { n: 1, title: "Build pressure", instruction: "With the engine running, let the compressor build air pressure up into the manufacturer's safe range.", tip: "Note roughly how long it takes — very slow build-up can indicate a fault." },
      { n: 2, title: "Low-pressure warning", instruction: "With the engine off, tap the brake pedal repeatedly to bleed pressure and confirm the low-pressure warning light/buzzer activates.", tip: "The warning must come on well before the spring brakes apply." },
      { n: 3, title: "Spring-brake apply", instruction: "Continue bleeding pressure and confirm the spring (parking) brakes apply automatically as pressure drops.", tip: "This fail-safe is exactly why a heavy vehicle must never be driven on low air." },
      { n: 4, title: "Re-build & release", instruction: "Restart, build pressure back into range and confirm the parking brake releases normally.", tip: "If it won't release, you do not have enough air — wait and recheck." },
    ],
    commonFaults: [
      "Not knowing where the safe pressure range is",
      "Driving off while the warning is still active",
      "Failing to confirm the spring-brake fail-safe",
    ],
  },
  {
    id: "hv_coupling",
    name: "Coupling a trailer",
    summary: "Connect a semi-trailer to the truck-tractor and confirm it's safe before moving.",
    difficulty: 3,
    estMinutes: 12,
    group: "heavy",
    steps: [
      { n: 1, title: "Line up & reverse", instruction: "Line the fifth wheel up squarely under the trailer kingpin and reverse slowly until the jaws engage with a clear lock.", tip: "Approach straight and slow — a crooked approach can damage the coupling or miss the lock." },
      { n: 2, title: "Visual lock check", instruction: "Get out and confirm the locking jaws have closed fully around the kingpin and the safety lock-pin is engaged.", tip: "A 'clunk' is not proof — you must see the jaws closed and the lock-pin in." },
      { n: 3, title: "Connect lines", instruction: "Connect the air lines (red emergency/supply and yellow service) and the electrical plug, checking for leaks and that all lights work.", tip: "Red = emergency/supply, yellow = service — a swapped or leaking line is dangerous." },
      { n: 4, title: "Raise the landing gear", instruction: "Wind the landing gear (support legs) fully up and stow the handle.", tip: "Legs left down can drag, catch the road, or be torn off." },
      { n: 5, title: "Tug test", instruction: "With the trailer brakes applied, gently drive the tractor forward against them to confirm the coupling holds.", tip: "If the tractor pulls away from the trailer, it is NOT locked — stop and re-couple." },
    ],
    commonFaults: [
      "Relying on the sound of the lock instead of a visual check",
      "Forgetting the tug test",
      "Leaving the landing gear partly down",
    ],
  },
  {
    id: "hv_uncoupling",
    name: "Uncoupling a trailer",
    summary: "Separate the trailer from the tractor safely, leaving it stable and secure.",
    difficulty: 2,
    estMinutes: 9,
    group: "heavy",
    steps: [
      { n: 1, title: "Park & secure", instruction: "Stop on firm, level ground, apply the trailer parking brake and chock the trailer wheels if needed.", tip: "Soft or sloping ground can let the trailer sink or roll once the tractor is gone." },
      { n: 2, title: "Lower the landing gear", instruction: "Wind the landing gear down until it just takes the trailer's weight off the fifth wheel.", tip: "Don't over-raise the trailer — it should sit level, taking its own weight." },
      { n: 3, title: "Disconnect lines", instruction: "Disconnect and stow the electrical plug and the air lines, capping or hanging them clear of the road.", tip: "Stow lines so they can't be crushed or dragged when you pull away." },
      { n: 4, title: "Release the coupling", instruction: "Pull the fifth-wheel release handle to free the locking jaws from the kingpin.", tip: "Make sure nothing (and no one) is between the units before you release." },
      { n: 5, title: "Pull away gently", instruction: "Ease the tractor forward slowly and smoothly out from under the trailer, watching your mirrors.", tip: "A sudden pull can damage the trailer or topple it if the landing gear isn't set." },
    ],
    commonFaults: [
      "Uncoupling on soft or sloping ground",
      "Pulling away with a line still connected",
      "Setting the landing gear too high or too low",
    ],
  },
  {
    id: "hv_incline_start",
    name: "Incline start (heavy vehicle)",
    summary: "Move a heavy vehicle off uphill without rolling back, using the parking brake.",
    difficulty: 3,
    estMinutes: 8,
    group: "heavy",
    steps: [
      { n: 1, title: "Held on the slope", instruction: "Stop on the incline with the parking (spring) brake applied and an appropriate low gear selected.", tip: "The spring brake — not the foot brake — is what holds a heavy vehicle on a slope." },
      { n: 2, title: "Build drive", instruction: "Raise the engine revs and bring the clutch to the biting point so you can feel the drive loading up.", tip: "A loaded heavy vehicle needs noticeably more drive than a car to hold against gravity." },
      { n: 3, title: "Release the parking brake", instruction: "Once drive is taking effect, release the parking brake smoothly so the vehicle moves forward, not back.", tip: "Releasing before the drive is loaded will let a heavy load roll back quickly." },
      { n: 4, title: "Move off", instruction: "Feed in throttle and ease the clutch fully out, pulling away under control and observing as you go.", tip: "Be patient and progressive — heavy vehicles reward smoothness, not speed." },
    ],
    commonFaults: [
      "Releasing the parking brake before the drive is loaded",
      "Rolling back into the space behind you",
      "Choosing too high a gear and stalling",
    ],
  },
  {
    id: "hv_straight_reverse",
    name: "Reverse in a straight line",
    summary: "Back a long vehicle down a marked lane using mirrors only, without touching the lines.",
    difficulty: 2,
    estMinutes: 9,
    group: "heavy",
    steps: [
      { n: 1, title: "Set up straight", instruction: "Stop with the vehicle (and trailer) dead straight in front of the lane — walk back and look if you're unsure.", tip: "Every degree of crookedness at the start multiplies as you reverse." },
      { n: 2, title: "Mirrors, not windows", instruction: "Reverse using both mirrors, comparing how much lane shows on each side of the vehicle.", tip: "Equal stripes of lane in both mirrors means you're straight — that's your instrument." },
      { n: 3, title: "Idle-speed creep", instruction: "Let the vehicle creep at idle, riding the clutch or brake gently — no throttle unless on a grade.", tip: "Slow gives your eyes time to catch drift while it's still a small correction." },
      { n: 4, title: "Correct early, correct small", instruction: "The moment one mirror shows more lane than the other, steer slightly toward the mirror with more space, then straighten.", tip: "Tiny early corrections beat big late ones — chasing a wobble makes it worse." },
      { n: 5, title: "Know your rear", instruction: "Stop where required, using a reference point for where the rear of the vehicle actually ends.", tip: "You're allowed to stop, get out and look — a look costs seconds, a line costs points." },
    ],
    commonFaults: [
      "Starting the reverse with the unit not straight",
      "Steering corrections that are too large and too late",
      "Rolling too fast to read the mirrors",
    ],
  },
  {
    id: "hv_alley_dock",
    name: "Alley docking (heavy vehicle)",
    summary: "Reverse into a side bay from a blind side, the way trucks meet loading docks.",
    difficulty: 3,
    estMinutes: 12,
    group: "heavy",
    steps: [
      { n: 1, title: "Position past the bay", instruction: "Drive past the dock and stop with the rear axle positioned so the tail can swing into the mouth of the bay.", tip: "The turning pivot is the rear axle, not the bumper — set up relative to it." },
      { n: 2, title: "Full lock, creep back", instruction: "Reverse at idle speed on full lock, watching the inside mirror as the rear swings toward the bay.", tip: "On the blind side, use the mirror plus a get-out-and-look — never guess." },
      { n: 3, title: "Chase the trailer (articulated)", instruction: "With a trailer, start the swing then steer back the other way to 'follow' the trailer into the bay.", tip: "Steer toward the trouble: if the trailer drifts left in the mirror, steer left to correct." },
      { n: 4, title: "Straighten inside", instruction: "As the unit enters the bay, unwind the lock so tractor and trailer line up parallel with the bay sides.", tip: "Aim to be straight before you're deep — you can't straighten against a wall." },
      { n: 5, title: "Finish within limits", instruction: "Stop fully inside the demarcated area, straight, without touching a line or kerb — pull forward once to correct if permitted.", tip: "A planned shunt (pull-forward) is worth more than a guessed line touch." },
    ],
    commonFaults: [
      "Setting up too close to the bay to swing the rear in",
      "Not getting out to check the blind side",
      "Over-steering the trailer and jackknifing the angle",
    ],
  },
  {
    id: "hv_turn_in_road",
    name: "Turn in the road",
    summary: "Turn a heavy vehicle to face the opposite direction inside a limited space.",
    difficulty: 3,
    estMinutes: 10,
    group: "heavy",
    steps: [
      { n: 1, title: "Scan the space", instruction: "Size up the full area first — kerbs, poles, camber and where each phase of the turn will end.", tip: "Plan all three moves before the first one; mid-manoeuvre improvisation is where kerbs get hit." },
      { n: 2, title: "First leg: full lock forward", instruction: "Move forward slowly on full right lock, using your mirrors to track both the front overhang and the tail swing.", tip: "The front corner sweeps far wider than the wheels — watch it against the far boundary." },
      { n: 3, title: "Stop short, wind off", instruction: "Stop before the front reaches the boundary and wind the steering the other way while stationary if needed.", tip: "With power steering, winding lock while stopped is acceptable here — hitting the kerb is not." },
      { n: 4, title: "Second leg: reverse on lock", instruction: "Reverse on full left lock, checking both mirrors and the rear boundary; stop with space for the final leg.", tip: "Long vehicles reverse further than feels natural — trust the mirror, not the panic." },
      { n: 5, title: "Final leg: drive out", instruction: "Pull forward, straightening up into the roadway facing the opposite direction, and cancel your signal.", tip: "Observation before every leg: mirror check, blind side, then move." },
    ],
    commonFaults: [
      "Touching a kerb or boundary with wheels or overhang",
      "Skipping the observation check between legs",
      "Running the front overhang over the boundary while watching only the wheels",
    ],
  },
  {
    id: "hv_wide_turns",
    name: "Left & right turns (long vehicle)",
    summary: "Take intersections without kerbing the trailer or inviting cars into your blind side.",
    difficulty: 3,
    estMinutes: 10,
    group: "heavy",
    steps: [
      { n: 1, title: "Set up early", instruction: "Signal early and position for the swept path: slightly wide of the kerb for a left turn so the rear wheels clear it.", tip: "The trailer's wheels cut the corner tighter than yours — the gap you leave is for them." },
      { n: 2, title: "Guard the inside", instruction: "Before turning left, check the left mirror for cyclists, bikes and cars sliding into the gap you opened.", tip: "Your turning gap looks like an invitation — assume someone has accepted it." },
      { n: 3, title: "Mirror through the turn", instruction: "Turn slowly, watching the inside mirror continuously as the rear wheels track toward the kerb.", tip: "Speed is the enemy: at walking pace you can stop the moment the mirror shows trouble." },
      { n: 4, title: "Mind the tail", instruction: "Remember the rear overhang swings the opposite way as you turn — check the outside mirror before committing.", tip: "Tail swing takes out poles and mirrors of parked cars on the side nobody watches." },
      { n: 5, title: "Straighten & confirm", instruction: "Complete the turn into the correct lane, cancel the indicator and re-check both mirrors.", tip: "A long vehicle isn't 'through' the turn until the last axle is — keep watching." },
    ],
    commonFaults: [
      "Rear wheels riding over the kerb on a left turn",
      "Not checking the left mirror for filtering traffic before turning",
      "Swinging out without watching the tail's opposite swing",
    ],
  },
  {
    id: "hv_road_ride",
    name: "Road drive: gears, brakes & space",
    summary: "The on-road discipline examiners score in a heavy vehicle: gear planning, smooth air brakes and space management.",
    difficulty: 2,
    estMinutes: 10,
    group: "heavy",
    steps: [
      { n: 1, title: "Plan gears ahead", instruction: "Read the road far ahead and change gear before you need it — approaching hills, turns and robots.", tip: "A heavy vehicle can't recover a missed gear under load; the plan IS the skill." },
      { n: 2, title: "Brake once, smoothly", instruction: "With air brakes, apply steady, progressive pressure early rather than pumping or stabbing.", tip: "Pumping air brakes wastes pressure; late braking with a load on is how intersections get overshot." },
      { n: 3, title: "Use engine & retarder", instruction: "Let engine braking and the retarder/exhaust brake hold your speed on descents, saving the service brakes.", tip: "Service brakes are for stopping; the driveline is for holding speed." },
      { n: 4, title: "Own more space", instruction: "Hold a following distance of six seconds or more — a loaded truck needs multiples of a car's stopping room.", tip: "Cars will cut into your gap; re-open it every time without frustration. That's the job." },
      { n: 5, title: "Constant observation", instruction: "Sweep all mirrors every few seconds, and check them before, during and after every speed or direction change.", tip: "A long vehicle changes the picture around it constantly — the mirrors are your only view of most of it." },
    ],
    commonFaults: [
      "Arriving at hills or robots in the wrong gear",
      "Stabbing at the brakes instead of one smooth application",
      "Letting the following gap collapse after being cut off",
    ],
  },
];

export const VEHICLE_DRIVER_MODULES: DriverModule[] = [...MOTORCYCLE_MODULES, ...HEAVY_MODULES];
