import type { Flashcard } from "@/types";

/**
 * Vehicle-code–specific flashcards — motorcycle (A1, A), heavy (10, 14) and a
 * couple of car-only (8) controls. Tagged with the codes they apply to so the
 * SRS queue only serves them to the relevant learners. Original wording derived
 * from official SA sources.
 */
export const VEHICLE_FLASHCARDS: Flashcard[] = [
  {
    id: "vf_mc_front_lever",
    categoryId: "controls",
    front: "Front brake lever",
    back: "Right handlebar, squeezed with right-hand fingers. Supplies most stopping power; combine with the rear brake for a balanced stop.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_rear_pedal",
    categoryId: "controls",
    front: "Rear brake pedal",
    back: "Pressed with the right foot. Used together with the front brake; on its own gives less stopping power and can lock the rear wheel more easily.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_clutch",
    categoryId: "controls",
    front: "Clutch lever",
    back: "Left handlebar, squeezed with left-hand fingers. Disengages drive from the rear wheel during gear changes and slow-speed control.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_throttle",
    categoryId: "controls",
    front: "Throttle (accelerator)",
    back: "Right handlebar grip; twist toward the rider to accelerate, away to decelerate. Spring-loaded back to idle.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_gear_pattern",
    categoryId: "controls",
    front: "Gear lever pattern",
    back: "Foot-operated on the left side: press down for 1st gear, lift up through the higher gears (1 down, rest up).",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_kill_switch",
    categoryId: "controls",
    front: "Engine cut-off switch",
    back: "Right handlebar, usually red. Stops the engine instantly without using the ignition key.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_front_brake_lean",
    categoryId: "controls",
    front: "Why not grab the front brake while leaning hard",
    back: "It can overload front-tyre grip and cause the front wheel to slide out, especially mid-corner.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_helmet",
    categoryId: "rules",
    front: "Helmet requirement",
    back: "Both the rider and any pillion passenger must wear a protective helmet, properly fastened, while the motorcycle is moving.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_a1_limit",
    categoryId: "rules",
    front: "Code A1 limit",
    back: "Code A1 covers light motorcycles with engine capacity not exceeding 125 cc; larger motorcycles require a full Code A licence.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_pillion",
    categoryId: "rules",
    front: "Pillion passenger rule",
    back: "A pillion passenger may only be carried where the motorcycle has a proper seat and footrests fitted for that passenger.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_lane_filtering",
    categoryId: "rules",
    front: "Lane filtering",
    back: "South African law does not grant motorcyclists a specific right to filter between lanes of traffic; the rider remains liable for any resulting collision.",
    difficulty: 2,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_prohibition_sign",
    categoryId: "signs",
    front: "Motorcycle-prohibition sign",
    back: "A red-circle sign with a motorcycle symbol and diagonal bar bans motorcycles from that road or section.",
    difficulty: 1,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_class_speed_sign",
    categoryId: "signs",
    front: "Class-specific speed sign",
    back: "A speed-limit sign with a motorcycle symbol/sub-plate applies that limit only to motorcycles, not to all traffic.",
    difficulty: 1,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_surface_hazards",
    categoryId: "hazard_awareness",
    front: "Road-surface hazards for riders",
    back: "Painted lines, manhole covers, gravel and fuel/oil spills are far more slippery for two wheels than four — extra caution is needed, especially in the wet.",
    difficulty: 1,
    codes: ["A1", "A"],
  },
  {
    id: "vf_mc_turbulence",
    categoryId: "hazard_awareness",
    front: "Wind/turbulence from large vehicles",
    back: "Passing close to or between large trucks can create turbulent air that pushes a lighter motorcycle sideways; anticipate and hold a firm, steady line.",
    difficulty: 1,
    codes: ["A1", "A"],
  },
  {
    id: "vf_hv_air_pressure",
    categoryId: "controls",
    front: "Air pressure build-up",
    back: "Before moving off, idle the engine until the air gauges reach the safe operating range — the vehicle must not move on low air pressure.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_spring_brake",
    categoryId: "controls",
    front: "Spring (parking) brake fail-safe",
    back: "Spring brakes are held off by air pressure; if air is lost, the springs apply automatically, bringing the vehicle to a stop.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_treadle",
    categoryId: "controls",
    front: "Foot brake (treadle) valve",
    back: "A wide pedal valve that releases air from the tanks to apply the service brakes on all coupled axles when pressed.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_diff_lock",
    categoryId: "controls",
    front: "Differential lock",
    back: "Forces both wheels on a drive axle to turn at the same speed for traction on loose/slippery ground; disengage again before turning on a hard, dry surface.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_retarder",
    categoryId: "controls",
    front: "Exhaust brake / retarder",
    back: "Provides extra engine braking on long descents, reducing wear and the risk of service-brake fade.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_fifth_wheel",
    categoryId: "controls",
    front: "Fifth-wheel coupling",
    back: "A plate-and-kingpin mechanism on the truck-tractor; the kingpin locks into spring-loaded jaws, secured by a safety lock-pin that must be visually confirmed before moving.",
    difficulty: 2,
    codes: ["14"],
  },
  {
    id: "vf_hv_tug_test",
    categoryId: "controls",
    front: "Tug test",
    back: "With the trailer brakes applied, gently drive the tractor forward; if it cannot pull away, the fifth-wheel coupling is confirmed locked.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_air_lines",
    categoryId: "controls",
    front: "Trailer air lines",
    back: "Yellow = service line (carries the brake-apply signal); Red = emergency/supply line (keeps the trailer tank charged and applies the brakes automatically if it fails).",
    difficulty: 2,
    codes: ["14"],
  },
  {
    id: "vf_hv_landing_gear",
    categoryId: "controls",
    front: "Landing gear",
    back: "The trailer's support legs; must be fully raised and secured before moving off, and lowered onto firm ground before uncoupling.",
    difficulty: 2,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_trailer_electrics",
    categoryId: "controls",
    front: "Trailer electrical connection",
    back: "A multi-pin plug (commonly 7-pin) supplying the trailer's indicators, brake lights, tail lights and reverse lights — test every function before moving.",
    difficulty: 2,
    codes: ["14"],
  },
  {
    id: "vf_hv_jackknife",
    categoryId: "hazard_awareness",
    front: "Jack-knifing",
    back: "Occurs when the trailer swings out of line with the tractor, most often triggered by harsh braking on a slippery surface.",
    difficulty: 1,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_stopping_distance",
    categoryId: "hazard_awareness",
    front: "Long stopping distances",
    back: "Greater mass, load and (for articulated units) tractor-trailer dynamics mean heavy vehicles need much more distance to stop than a car.",
    difficulty: 1,
    codes: ["14"],
  },
  {
    id: "vf_hv_following_distance",
    categoryId: "following_distance",
    front: "Extra distance for heavy vehicles",
    back: "Longer stopping distances and larger blind spots mean a heavy-vehicle driver needs a greater following distance than a car driver.",
    difficulty: 1,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_mass_sign",
    categoryId: "signs",
    front: "Mass-limit sign",
    back: "A truck symbol with a mass figure prohibits vehicles whose gross vehicle mass exceeds that figure from using the road.",
    difficulty: 1,
    codes: ["10", "14"],
  },
  {
    id: "vf_hv_height_sign",
    categoryId: "signs",
    front: "Height-restriction sign",
    back: "Warns that a vehicle taller than the stated clearance will strike the bridge/tunnel structure ahead.",
    difficulty: 1,
    codes: ["10", "14"],
  },
  {
    id: "vf_car_auto_selector",
    categoryId: "controls",
    front: "Automatic transmission selector",
    back: "P (Park) - R (Reverse) - N (Neutral) - D (Drive); replaces the clutch pedal and manual gear lever.",
    difficulty: 1,
    codes: ["8"],
  },
  {
    id: "vf_car_epb",
    categoryId: "controls",
    front: "Electronic parking brake",
    back: "A dash/console switch that electrically applies the rear brakes to hold the car stationary, replacing a manual handbrake lever on many newer models.",
    difficulty: 1,
    codes: ["8"],
  },
];
