// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/gen-content-meta.mjs
// Kept honest by tests/content-meta.test.ts, which fails if this drifts from
// the real content bank.
//
// The planning index: what the study store needs to size a session, count what
// is due and award CP, with none of the material a learner is paying to see.
// Importing the full bank for this is what shipped every question and answer to
// every route that mounts the store.
import type { CategoryId, Difficulty, VehicleCode } from "@/types";

export interface ContentMeta {
  id: string;
  categoryId: CategoryId;
  /** Absent means "applies to every licence code" — see forCode(). */
  codes?: VehicleCode[];
}

/** Scenario tasks surface their title as the plan subtitle, so labels ride along. */
export interface ScenarioMeta extends ContentMeta {
  title: string;
}

/** Question id -> difficulty (1-3). The only question field CP scoring reads. */
export const QUESTION_DIFFICULTY: Record<string, number> = {
  "q_sign_stop": 1,
  "q_sign_yield": 1,
  "q_sign_yield_ped": 2,
  "q_sign_ped_priority": 3,
  "q_sign_circle": 2,
  "q_sign_no_entry": 1,
  "q_sign_one_way": 2,
  "q_sign_no_left": 1,
  "q_sign_no_uturn": 1,
  "q_sign_no_parking": 2,
  "q_sign_no_overtaking": 2,
  "q_sign_speed_limit": 1,
  "q_sign_robot_red": 1,
  "q_sign_robot_amber": 2,
  "q_sign_flashing_red": 2,
  "q_sign_ped_warn": 1,
  "q_sign_ped_crossing": 1,
  "q_sign_children": 1,
  "q_sign_cyclists": 2,
  "q_sign_gate_boom": 2,
  "q_sign_railway": 2,
  "q_sign_steep_descent": 2,
  "q_sign_reg_shape": 1,
  "q_sign_warn_shape": 1,
  "q_sign_info_colour": 2,
  "q_sign_default_urban": 1,
  "q_sign_default_rural": 2,
  "q_sign_broken_white": 2,
  "q_sign_solid_white": 2,
  "q_sign_yellow_line": 3,
  "q_sign_red_line_kerb": 3,
  "q_sign_box_junction": 3,
  "q_sign_green_route": 2,
  "q_sign_de_restriction": 3,
  "q_sign_freeway_start": 2,
  "q_ctrl_clutch": 1,
  "q_ctrl_accelerator": 1,
  "q_ctrl_footbrake": 2,
  "q_ctrl_handbrake": 2,
  "q_ctrl_handbrake_motion": 2,
  "q_ctrl_clutch_control": 2,
  "q_ctrl_temp": 2,
  "q_ctrl_abs": 2,
  "q_ctrl_mirrors": 2,
  "q_ctrl_steering": 1,
  "q_ctrl_headlights": 2,
  "q_ctrl_indicator": 2,
  "q_ctrl_engine_braking": 3,
  "q_ctrl_fuel_warning": 1,
  "q_rules_freeway_speed": 1,
  "q_rules_alcohol": 2,
  "q_rules_seatbelt": 2,
  "q_rules_seatbelt_moving": 1,
  "q_rules_hand_signal": 2,
  "q_rules_hand_freeway": 3,
  "q_rules_keep_left": 1,
  "q_rules_divided_solid": 2,
  "q_rules_overtake_blind": 2,
  "q_rules_overtake_left": 3,
  "q_rules_being_overtaken": 2,
  "q_rules_turn_right_position": 2,
  "q_rules_emergency_triangle": 2,
  "q_rules_tread": 2,
  "q_rules_lights_on": 2,
  "q_rules_cellphone": 1,
  "q_rules_ped_collision": 3,
  "q_rules_emergency_vehicle": 2,
  "q_rules_freeway_stop": 2,
  "q_rules_learner_freeway": 2,
  "q_rules_unattended": 2,
  "q_int_4way_order": 2,
  "q_int_4way_same_time": 2,
  "q_int_circle": 2,
  "q_int_mini_circle": 3,
  "q_int_robot_dead": 2,
  "q_int_turn_right": 2,
  "q_int_yield_sign": 2,
  "q_int_green_arrow": 2,
  "q_int_t_junction": 2,
  "q_int_emergency_intersection": 3,
  "q_int_ped_crossing": 2,
  "q_int_blocked": 2,
  "q_park_crossing": 3,
  "q_park_intersection": 3,
  "q_park_facing": 2,
  "q_park_bay": 1,
  "q_park_hydrant": 2,
  "q_park_bridge": 3,
  "q_park_incline_down": 3,
  "q_park_incline_up": 3,
  "q_park_no_stopping": 2,
  "q_park_disabled": 1,
  "q_fd_two_second": 1,
  "q_fd_measure": 2,
  "q_fd_wet": 2,
  "q_fd_truck": 2,
  "q_fd_tailgated": 2,
  "q_fd_braking": 3,
  "q_fd_thinking": 2,
  "q_fd_night": 2,
  "q_fd_downhill": 2,
  "q_haz_scan": 1,
  "q_haz_children": 2,
  "q_haz_fatigue": 2,
  "q_haz_blind_spot": 1,
  "q_haz_aquaplane": 3,
  "q_haz_ball": 2,
  "q_haz_skid": 3,
  "q_haz_sun_glare": 2,
  "q_haz_animal_night": 2,
  "q_haz_brake_fail": 3,
  "vq_mc_front_brake": 1,
  "vq_mc_front_brake_turn": 2,
  "vq_mc_clutch_moveoff": 1,
  "vq_mc_gear_pattern": 2,
  "vq_mc_prohibition_sign": 1,
  "vq_mc_class_speed_sign": 2,
  "vq_mc_helmet": 1,
  "vq_mc_a1_capacity": 1,
  "vq_mc_pillion": 2,
  "vq_mc_surface_hazards": 2,
  "vq_mc_truck_turbulence": 2,
  "vq_mc_following_distance": 2,
  "vq_mc_incline_start": 3,
  "vq_mc_emergency_stop": 3,
  "vq_mc_slow_ride": 3,
  "vq_mc_swerve": 3,
  "vq_mc_parking": 1,
  "vq_mc_four_way_stop": 1,
  "vq_mc_lane_filtering": 3,
  "vq_mc_kill_switch": 1,
  "vq_hv_air_pressure": 1,
  "vq_hv_spring_brake": 2,
  "vq_hv_emergency_line": 2,
  "vq_hv_service_line": 2,
  "vq_hv_fifth_wheel_check": 2,
  "vq_hv_tug_test": 3,
  "vq_hv_landing_gear": 1,
  "vq_hv_diff_lock": 2,
  "vq_hv_diff_lock_turn": 3,
  "vq_hv_retarder": 2,
  "vq_hv_jackknife": 2,
  "vq_hv_stopping_distance": 2,
  "vq_hv_following_distance": 2,
  "vq_hv_mass_sign": 2,
  "vq_hv_height_sign": 1,
  "vq_hv_definition": 2,
  "vq_hv_code14_gcm": 2,
  "vq_hv_prdp": 1,
  "vq_hv_air_tank_water": 3,
  "vq_hv_wide_turn": 2,
  "q2_sign_one_way_right": 1,
  "q2_sign_no_right": 1,
  "q2_sign_robot_green": 1,
  "q2_sign_steep_ascent": 2,
  "q2_sign_temp_yellow": 2,
  "q2_sign_guidance_green": 1,
  "q2_sign_brown_tourism": 1,
  "q2_sign_warn_tjunction": 1,
  "q2_sign_slippery": 2,
  "q2_sign_road_narrows": 2,
  "q2_sign_two_way": 1,
  "q2_sign_gravel_begins": 2,
  "q2_sign_wild_animals": 2,
  "q2_sign_command_blue": 2,
  "q2_sign_stop_vs_yield_line": 2,
  "q2_sign_painted_island": 2,
  "q2_sign_lane_arrows": 2,
  "q2_sign_bus_lane": 2,
  "q2_sign_school_patrol": 1,
  "q2_sign_rumble_strips": 1,
  "q2_sign_clearance": 2,
  "q2_sign_officer_overrides": 1,
  "q2_sign_ped_blocks": 1,
  "q2_sign_speed_hump": 1,
  "q2_rules_accident_duty": 2,
  "q2_rules_tow_rope_speed": 2,
  "q2_rules_tow_gap": 3,
  "q2_rules_caravan_people": 1,
  "q2_rules_load_rear": 3,
  "q2_rules_door_open": 1,
  "q2_rules_reversing": 1,
  "q2_rules_coasting": 2,
  "q2_rules_hooter": 1,
  "q2_rules_night_parked_lights": 3,
  "q2_rules_cyclist_gap": 1,
  "q2_rules_ped_freeway": 1,
  "q2_rules_beam_reach": 3,
  "q2_rules_bus_speed": 2,
  "q2_rules_livestock": 1,
  "q2_rules_throwing": 1,
  "q2_rules_licence_carry": 1,
  "q2_rules_prof_alcohol": 2,
  "q2_rules_learner_ages": 2,
  "q2_rules_learner_validity": 1,
  "q2_ctrl_hazards": 1,
  "q2_ctrl_wipers_demister": 1,
  "q2_ctrl_oil_light": 2,
  "q2_ctrl_battery_light": 2,
  "q2_ctrl_seat_setup": 1,
  "q2_ctrl_headrest": 2,
  "q2_ctrl_ignition_moving": 2,
  "q2_ctrl_dry_steering": 3,
  "q2_int_uncontrolled": 2,
  "q2_int_left_position": 1,
  "q2_int_multilane_circle": 2,
  "q2_int_green_ped_still": 1,
  "q2_int_red_arrow": 2,
  "q2_int_rail_multi_track": 2,
  "q2_int_slipway": 2,
  "q2_park_narrow_road": 3,
  "q2_park_direction": 2,
  "q2_park_kerb_gap": 2,
  "q2_park_bus_stop": 1,
  "q2_park_double": 1,
  "q2_park_unattended_check": 1,
  "q2_fd_three_second": 1,
  "q2_fd_stopped_hill": 2,
  "q2_fd_gravel": 2,
  "q2_fd_reaction_100": 3,
  "q2_fd_taxi_gap": 1,
  "q2_haz_night_rural": 2,
  "q2_haz_pothole": 3,
  "q2_haz_fog_bank": 2,
  "q2_haz_blowout": 3,
  "q2_haz_oncoming_overtaker": 2,
  "q2_haz_first_rain": 3,
  "q2_haz_night_glare": 2,
  "q2_haz_breakdown_freeway": 2,
  "q2_car_child_restraint": 1,
  "q2_car_airbag_childseat": 2,
  "q2_car_auto_feet": 1,
  "q2_car_power_steering": 3,
  "q2_car_cruise_wet": 3,
  "q2_car_spare_kit": 1,
  "q2_mc_headlight_always": 1,
  "q2_mc_learner_pillion": 1,
  "q2_mc_gear_beyond_helmet": 1,
  "q2_mc_visor": 2,
  "q2_mc_tyre_check": 1,
  "q2_mc_chain": 2,
  "q2_mc_paint_wet": 2,
  "q2_mc_pillion_rules": 2,
  "q2_mc_target_fixation": 2,
  "q2_mc_group_riding": 2,
  "q2_hv_arrester_bed": 2,
  "q2_hv_descent_gear": 2,
  "q2_hv_blind_spots": 2,
  "q2_hv_load_secure": 2,
  "q2_hv_height_route": 3,
  "q2_hv_tail_swing": 3,
  "q2_hv_speed_80": 2,
  "q2_hv_moving_brake_test": 2,
  "q2_hv_prdp_dangerous": 3,
  "q2_hv_fatigue_plan": 1,
  "q3_park_kerb_distance": 2,
  "q3_park_direction": 1,
  "q3_park_intersection": 2,
  "q3_park_freeway": 1,
  "q3_park_engine": 1,
  "q3_park_crossing": 1,
  "q3_park_driveway": 1,
  "q3_park_hill_kerb": 2,
  "q3_park_night_rural": 2,
  "q3_park_disabled_bay": 1,
  "q3_park_yellow_line": 2,
  "q3_park_reverse_bay": 2,
  "q3_fd_two_second_how": 1,
  "q3_fd_wet": 1,
  "q3_fd_stopping_parts": 2,
  "q3_fd_speed_square": 3,
  "q3_fd_tailgater": 2,
  "q3_fd_stopped_tyres": 2,
  "q3_fd_heavy_ahead": 1,
  "q3_fd_night": 2,
  "q3_fd_being_overtaken": 1,
  "q3_fd_motorcycle_gap": 2,
  "q3_int_four_way": 1,
  "q3_int_dead_robot": 1,
  "q3_int_turn_right": 2,
  "q3_int_blocked": 2,
  "q3_int_circle_yield": 2,
  "q3_int_mini_circle": 3,
  "q3_int_emergency": 2,
  "q3_int_lane_choice": 1,
  "q3_int_amber": 1,
  "q3_int_scholar_patrol": 1,
  "q3_rule_speed_urban": 1,
  "q3_rule_speed_freeway": 1,
  "q3_rule_bac": 2,
  "q3_rule_learner_age": 1,
  "q3_rule_learner_supervision": 1,
  "q3_rule_demerit_learner": 3,
  "q3_rule_demerit_expiry": 3,
  "q3_rule_cellphone": 1,
  "vx_mc_learner_passenger": 1,
  "vx_mc_helmet_both": 1,
  "vx_mc_daytime_headlight": 1,
  "vx_mc_a1_capacity": 1,
  "vx_mc_lifesaver": 2,
  "vx_mc_wet_paint": 2,
  "vx_mc_following_wet": 1,
  "vx_mc_blind_spot_position": 2,
  "vx_mc_truck_wind": 2,
  "vx_mc_passenger_rules": 2,
  "vx_mc_gravel_braking": 2,
  "vx_mc_load_balance": 2,
  "vx_hv_speed_limit": 2,
  "vx_hv_code10_gvm": 2,
  "vx_hv_downhill_gear": 2,
  "vx_hv_air_pressure": 2,
  "vx_hv_arrester_bed": 2,
  "vx_hv_tail_swing": 2,
  "vx_hv_following_distance": 1,
  "vx_hv_load_secure": 2,
  "vx_hv_height_clearance": 1,
  "vx_hv_spray_rain": 2,
  "vx_hv_railway_clearance": 2,
  "vx_hv_overtaking_time": 2,
  "q4_sign_grammar_red_ring": 1,
  "q4_sign_grammar_blue": 1,
  "q4_sign_grammar_triangle": 1,
  "q4_sign_temporary": 2,
  "q4_sign_shapes_unique": 3,
  "q4_sign_headlights_cmd": 2,
  "q4_sign_pass_side": 2,
  "q4_sign_proceed_direction": 2,
  "q4_sign_circle_clockwise": 2,
  "q4_sign_no_left_int": 1,
  "q4_sign_no_ot_trucks": 2,
  "q4_sign_no_hooter": 2,
  "q4_sign_reserved_lane": 2,
  "q4_sign_no_stopping_vs_parking": 2,
  "q4_sign_derestriction": 3,
  "q4_sign_stop_vs_yield": 1,
  "q4_sign_no_entry_vs_oneway": 1,
  "q4_sign_robot_amber_meaning": 1,
  "q4_sign_flashing_red": 2,
  "q4_sign_green_arrow": 2,
  "q4_sign_railway_action": 1,
  "q4_sign_children_response": 1,
  "q4_sign_steep_descent_action": 2,
  "q4_sign_speed_min": 3,
  "q4_sign_guidance_green": 1,
  "q4_sign_brown_tourism": 1,
  "q4_mark_stop_line": 1,
  "q4_mark_centre_broken": 1,
  "q4_mark_barrier_side": 2,
  "q4_mark_painted_island": 2,
  "q4_mark_yellow_edge": 2,
  "q4_mark_arrow_lane": 2,
  "q4_mark_ped_block": 1,
  "q5_rule_freeway_banned": 2,
  "q5_rule_freeway_cross": 1,
  "q5_rule_freeway_reverse": 1,
  "q5_rule_lights_when": 2,
  "q5_rule_dim_oncoming": 1,
  "q5_rule_parked_visible": 2,
  "q5_rule_belt_responsible": 2,
  "q5_rule_infant_restraint": 2,
  "q5_rule_child_no_seat": 2,
  "q5_rule_overtake_left": 2,
  "q5_rule_overtake_where_not": 2,
  "q5_rule_being_overtaken": 1,
  "q5_rule_emergency_duty": 1,
  "q5_rule_officer_overrides": 2,
  "q5_rule_herded_animals": 2,
  "q5_rule_coasting": 2,
  "q5_rule_reversing": 2,
  "q5_rule_view_obstruction": 1,
  "q5_rule_hooter_use": 1,
  "q5_rule_unattended_kids": 3,
  "q5_rule_following_emergency_scene": 1,
  "q5_rule_hand_signal_right": 2,
  "q5_rule_signal_timing": 1,
  "q6_mark_double_solid": 2,
  "q6_mark_cross_barrier_legal": 2,
  "q6_mark_white_edge": 2,
  "q6_mark_yellow_freeway_shoulder": 2,
  "q6_mark_studs_white": 3,
  "q6_mark_studs_red": 3,
  "q6_mark_box_junction": 2,
  "q6_mark_keep_clear": 1,
  "q6_mark_stop_line_setback": 2,
  "q6_mark_lane_reduction": 2,
  "q6_mark_chevron_barrier": 3,
  "q6_temp_yellow_force": 1,
  "q6_temp_why_yellow": 2,
  "q6_temp_flagperson": 1,
  "q6_temp_speed_zone": 1,
  "q6_temp_cones": 1,
  "q6_temp_detour": 1,
  "q6_temp_vs_permanent": 2,
  "q6_temp_workers_end": 2,
  "q6_mark_speed_hump": 1,
  "q6_mark_kerb_paint": 2,
  "q7_int_given_not_taken": 2,
  "q7_int_stop_street_empty": 1,
  "q7_int_yield_vs_stop": 1,
  "q7_int_uncontrolled_right": 2,
  "q7_int_minor_major": 2,
  "q7_int_stale_green": 2,
  "q7_int_turn_right_no_arrow": 3,
  "q7_int_green_still_yield": 2,
  "q7_int_left_cyclist": 2,
  "q7_int_two_right_lanes": 3,
  "q7_int_observation_sequence": 1,
  "q7_int_oncoming_both_right": 1,
  "q7_int_circle_signal_exit": 3,
  "q7_int_circle_no_stop": 3,
  "q7_int_circle_gap": 2,
  "q7_int_zip_merge": 2,
  "q7_int_blind_junction": 2,
  "q7_int_ped_already_crossing": 1,
  "q7_int_emergency_side": 2,
  "q7_int_left_turn_lane_discipline": 1,
  "q8_ctrl_two_parts": 1,
  "q8_ctrl_yard_manoeuvres": 2,
  "q8_ctrl_incline_rollback": 1,
  "q8_ctrl_yard_contact": 2,
  "q8_ctrl_alley_dock": 2,
  "q8_ctrl_observe_every_move": 2,
  "q8_ctrl_moving_off_look": 1,
  "q8_ctrl_reverse_observe": 2,
  "q8_ctrl_steering_method": 2,
  "q8_ctrl_wheel_recovery": 2,
  "q8_ctrl_hands_on": 1,
  "q8_ctrl_cockpit_order": 2,
  "q8_ctrl_pretrip_exterior": 1,
  "q8_ctrl_start_neutral": 1,
  "q8_ctrl_ride_clutch": 2,
  "q8_ctrl_reverse_stationary": 1,
  "q8_ctrl_right_gear": 2,
  "q8_ctrl_cover_brake": 2,
  "q8_ctrl_stall_recovery": 2,
  "q8_ctrl_progressive_brake": 1,
  "q9_haz_scan_ahead": 2,
  "q9_haz_space_cushion": 2,
  "q9_haz_crosswind": 2,
  "q9_haz_smoke": 1,
  "q9_haz_stray_animal": 2,
  "q9_haz_road_rage": 1,
  "q9_haz_medication": 2,
  "q9_haz_stationary_bus": 1,
  "q9_haz_debris_swerve": 2,
  "q9_park_hill_no_kerb": 3,
  "q9_park_secure_steep": 2,
  "q9_park_leaving_bay": 1,
  "q9_park_dooring": 1,
  "q9_park_pavement": 1,
  "q9_park_corner_visibility": 2,
  "q9_park_obstruct_line": 2,
  "q9_park_angle_reverse": 2,
  "q9_fd_towing": 2,
  "q9_fd_erratic": 1,
  "q9_fd_worn_loaded": 2,
  "q9_fd_sides": 2,
  "q9_fd_why_seconds": 2,
  "q9_fd_helps_behind": 3,
  "q9_fd_approach_queue": 1,
  "q9_fd_new_driver_gap": 1,
  "q10_mc_countersteer": 3,
  "q10_mc_lane_position": 2,
  "q10_mc_cornering": 3,
  "q10_mc_both_brakes": 2,
  "q10_mc_smidsy": 2,
  "q10_mc_gravel": 3,
  "q10_mc_preride": 1,
  "q10_mc_stop_position": 2,
  "q10_mc_look_through": 2,
  "q10_mc_wind_blast": 2,
  "q10_mc_pillion": 2,
  "q10_hv_low_air": 2,
  "q10_hv_rollover": 2,
  "q10_hv_offtracking": 3,
  "q10_hv_coupling_lock": 3,
  "q10_hv_reverse_artic": 3,
  "q10_hv_axle_load": 3,
  "q10_hv_overload_effect": 2,
  "q10_hv_dangerous_goods": 2,
  "q10_hv_dual_tyre": 2,
  "q10_hv_uncouple": 3,
  "q10_hv_brake_fade": 2,
  "q11_park_stop_vs_park": 2,
  "q11_park_hydrant_reason": 1,
  "q11_park_verge_pedestrians": 1,
  "q11_fd_night_headlights": 2,
  "q11_fd_cut_in": 2,
  "q11_fd_approaching_queue": 2,
  "q11_int_amber_meaning": 1,
  "q11_int_second_train": 2,
  "q11_int_scholar_patrol": 1,
  "q11_haz_low_sun": 2,
  "q11_haz_total_brake_failure": 3,
  "q11_haz_freeway_breakdown": 2,
  "q11_haz_oncoming_in_lane": 3,
  "aarto_q_start_date": 2,
  "aarto_q_what_is": 1,
  "aarto_q_learner_threshold": 2,
  "aarto_q_licensed_threshold": 2,
  "aarto_q_excess_suspension": 3,
  "aarto_q_expiry": 2,
  "aarto_q_paying_fine": 3,
  "aarto_q_no_licence_points": 3,
  "aarto_q_stop_street_points": 2,
  "aarto_q_cancellation": 3,
  "aarto_q_when_added": 3,
  "aarto_q_why_learners_care": 2,
  "aarto_q_full_name": 2,
  "aarto_q_clean_record": 1,
  "qx_ctrl_seat_distance": 1,
  "qx_ctrl_interior_mirror_aim": 1,
  "qx_ctrl_side_mirror_aim": 2,
  "qx_ctrl_blind_spot_meaning": 1,
  "qx_ctrl_doors_closed": 1,
  "qx_ctrl_seatbelt_before_start": 1,
  "qx_ctrl_brake_warning_light": 2,
  "qx_ctrl_engine_light": 2,
  "qx_ctrl_speedometer": 1,
  "qx_ctrl_abs_pedal_feel": 2,
  "qx_ctrl_clutch_before_stop": 2,
  "qx_ctrl_eyes_on_road_gear": 1,
  "qx_ctrl_coasting_neutral": 2,
  "qx_ctrl_moveoff_sequence": 2,
  "qx_ctrl_handbrake_at_stop": 2,
  "qx_ctrl_reverse_speed": 2,
  "qx_ctrl_no_crossing_arms": 2,
  "qx_ctrl_turn_in_road_purpose": 2,
  "qx_ctrl_parallel_finish": 2,
  "qx_ctrl_yard_time_limit": 3,
  "qx_ctrl_observation_before_reverse": 2,
  "qx_ctrl_signal_timing": 1,
  "qx_ctrl_signal_no_permission": 2,
  "qx_ctrl_brake_light_check": 2,
  "qx_ctrl_misting_demister": 1,
  "qx_ctrl_washer_wiper_pretrip": 1,
  "qx_ctrl_securing_on_leaving": 1,
  "qx_ctrl_handbrake_hard_park": 2,
  "qx_ctrl_auto_selector_stationary": 2,
  "qx_ctrl_auto_creep": 1,
  "qx_ctrl_tyre_blowout": 3,
  "qx_ctrl_brake_fade": 3,
  "qx_ctrl_stuck_accelerator": 3,
  "qx_ctrl_wet_brake_dry": 3,
  "qx_ctrl_power_steering_heavy": 3,
  "qr2_right_of_way_given": 2,
  "qr2_funeral_procession": 2,
  "qr2_roadblock": 1,
  "qr2_yield_to_pedestrian_turning": 2,
  "qr2_animal_drawn": 2,
  "qr2_headlights_courtesy": 2,
  "qr2_slow_vehicle_courtesy": 2,
  "qr2_lights_dusk": 2,
  "qr2_box_junction_entry": 2,
  "qr2_stop_line_position": 3,
  "qr2_turn_across_queue": 3,
  "qr2_traffic_circle_exit_signal": 2,
  "qr2_yield_no_stop_needed": 2,
  "qr2_blocked_view_junction": 2,
  "qr2_emergency_at_red": 3,
  "qr2_left_turn_cyclist": 2,
  "qr2_park_against_flow": 2,
  "qr2_park_obstruct_sign": 2,
  "qr2_park_loading_zone": 2,
  "qr2_park_kerb_side_urban": 2,
  "qr2_park_children_exit": 1,
  "qr2_park_hazard_lights_myth": 2,
  "qr2_following_reason_space": 1,
  "qr2_following_view_ahead": 2,
  "qr2_following_gap_closed": 2,
  "qr2_following_downhill_load": 2,
  "qr2_following_stale_gap": 2,
  "qr2_hazard_scan_pattern": 2,
  "qr2_hazard_escape_route": 3,
  "qr2_hazard_covering_children": 1,
  "qr2_hazard_indicator_trust": 2,
  "qr2_hazard_wet_first_rain": 2,
  "qr2_hazard_emerging_vehicle": 2,
  "qr2_hazard_overload_visibility": 2,
  "qs2_curve_single": 1,
  "qs2_curve_series": 2,
  "qs2_hairpin": 2,
  "qs2_dip": 2,
  "qs2_uneven": 1,
  "qs2_two_way_resumes": 2,
  "qs2_slippery": 1,
  "qs2_falling_rocks": 2,
  "qs2_side_wind": 2,
  "qs2_causeway": 3,
  "qs2_loose_stones": 2,
  "qs2_farm_animals": 1,
  "qs2_cyclists_ahead": 1,
  "qs2_signals_ahead": 2,
  "qs2_yield_ahead": 2,
  "qs2_tunnel": 2,
  "qs2_height_limit": 2,
  "qs2_width_limit": 2,
  "qs2_length_limit": 3,
  "qs2_mass_limit": 2,
  "qs2_minimum_speed": 2,
  "qs2_keep_left": 2,
  "qs2_no_towing": 2,
  "qs2_no_pedestrians_sign": 1,
  "qs2_dangerous_goods_prohibited": 3,
  "qs2_compulsory_ahead": 1,
  "qs2_no_through_road": 1,
  "qs2_hospital_sign": 1,
  "qs2_rest_area": 1,
  "qs2_emergency_phone": 2,
  "qs2_route_marker_shape": 2,
  "qs2_blue_vs_red_circle": 2,
  "qs2_warning_vs_regulatory": 2,
  "qs2_sign_placement_distance": 2,
  "qs2_supplementary_plate": 3,
  "qs2_sign_conflict_officer": 2,
  "qs2_faded_sign": 2,
  "qs2_chevron_board": 2,
  "qs2_hazard_marker": 2,
  "qs2_delineator_posts": 2,
  "qs2_st_andrews_cross": 2,
  "qs2_crossing_flashing_red": 1,
  "qs2_freeway_ends": 2,
  "qs2_lane_control_x": 2,
  "qs2_climbing_lane": 2,
  "qs2_exit_number": 2,
  "qs2_distance_board": 1,
  "qs2_end_of_restriction": 2,
  "qs2_restriction_until_cancelled": 3,
  "qs2_speed_limit_is_maximum": 1,
  "qc3_handbrake_partly_on": 2,
  "qc3_spongy_pedal": 2,
  "qc3_pulls_under_braking": 3,
  "qc3_steering_play": 3,
  "qc3_bonnet_unlatched": 1,
  "qc3_windscreen_chip": 1,
  "qc3_low_pressure_handling": 2,
  "qc3_wheel_nuts_recheck": 2,
  "qc3_warning_triangle_place": 2,
  "qc3_headlight_aim_loaded": 3,
  "qc3_jump_start_order": 2,
  "qc3_fog_lights_use": 2,
  "qc3_cruise_control_when_not": 2,
  "qc3_block_gear_change": 3,
  "qc3_over_revving": 2,
  "qc3_convex_mirror_distance": 3,
  "qr3_level_crossing_room": 2,
  "qr3_collision_duty": 2,
  "qr3_tow_rope_steering": 2,
  "qr3_hazards_while_moving": 2,
  "qr3_yellow_lane_not_a_lane": 2,
  "qr3_rear_seatbelts": 1,
  "qr3_projecting_load_marked": 2,
  "qr3_plates_legible": 1,
  "qr3_stationary_bus": 2,
  "qr3_footwear_control": 2,
  "qr3_keep_clear_marking": 2,
  "qr3_slip_lane_merge": 2,
  "qr3_green_but_pedestrian": 1,
  "qr3_right_from_oneway": 3,
  "qr3_circle_exit_crossing": 2,
  "qr3_turn_across_cycle_lane": 2,
  "qr3_yield_line_position": 2,
  "qr3_blocked_box_wait": 2,
  "qr3_two_lane_circle_position": 3,
  "qr3_scholar_patrol_authority": 1,
  "qr3_park_taxi_rank": 1,
  "qr3_park_traffic_island": 2,
  "qr3_park_school_gate": 1,
  "qr3_park_meter_expired": 1,
  "qr3_park_verge_services": 2,
  "qr3_park_abreast": 1,
  "qr3_park_angle_reverse_in": 2,
  "qr3_park_ev_bay": 1,
  "qr3_fd_being_overtaken": 2,
  "qr3_fd_lateral_space": 3,
  "qr3_fd_convoy": 2,
  "qr3_fd_dazzle_gap": 2,
  "qr3_fd_emergency_lane_gap": 3,
  "qr3_fd_tunnel_gap": 2,
  "qr3_hz_reversing_lights": 2,
  "qr3_hz_low_sun_others": 3,
  "qr3_hz_wet_leaves_mud": 2,
  "qr3_hz_queue_hazards": 2,
  "qr3_hz_animals_night": 2,
  "qr3_hz_load_shifting": 2,
  "qr4_reckless_vs_negligent": 3,
  "qr4_refusing_test": 2,
  "qr4_racing_public_road": 1,
  "qr4_obey_officer": 2,
  "qr4_produce_licence": 1,
  "qr4_roadworthy_purpose": 2,
  "qr4_learner_supervision": 2,
  "qr4_licence_disc_display": 1,
  "qr4_obstruction_offence": 3,
  "qr4_pavement_driving": 1,
  "qr4_reverse_freeway": 1,
  "qr4_passengers_goods_area": 2,
  "qr4_pedestrian_facing_traffic": 2,
  "qr4_cyclist_single_file": 2,
  "qr4_solid_line_crossing": 3,
  "qr4_hooter_at_night": 2,
  "qr4_aarto_points_mechanic": 2,
  "qr4_aarto_paying_fine": 3,
  "qr4_narrow_bridge_priority": 3,
  "qr4_emergency_stopped_shoulder": 2,
  "qr4_flashing_amber_signal": 2,
  "qr4_turn_on_arrow_only": 2,
  "qr4_uncontrolled_equal_roads": 2,
  "qr4_pedestrian_crossing_overtake": 2,
  "qr4_turning_traffic_yield_straight": 1,
  "qr4_stop_line_missing": 2,
  "qr4_park_facing_wrong_night": 2,
  "qr4_park_blocking_hydrant": 1,
  "qr4_park_across_two_bays": 1,
  "qr4_park_engine_running_unattended": 1,
  "qr4_park_narrow_road_both_sides": 2,
  "qr4_fd_assured_clear_distance": 3,
  "qr4_fd_two_second_why_time": 2,
  "qr4_fd_headlight_overdrive": 3,
  "qr4_fd_wet_grip_loss": 2,
  "qr4_hz_fatigue_only_cure": 1,
  "qr4_hz_microsleep": 2,
  "qr4_hz_medication": 2,
  "qr4_hz_phone_handsfree": 3,
  "qr4_hz_first_rain_oil": 2,
  "qr4_hz_aquaplane_response": 3,
  "qc4_mirror_night_setting": 2,
  "qc4_seatbelt_lap_position": 2,
  "qc4_seat_belt_twisted": 2,
  "qc4_auto_lower_range_descent": 2,
  "qc4_hot_coolant_cap": 2,
  "qc4_oil_check_method": 2,
  "qc4_jack_safety": 3,
  "qc4_space_saver_spare": 2,
  "qc4_roof_load_handling": 3,
  "qc4_boot_load_placement": 3,
  "qc4_loose_items_cabin": 2,
  "qc4_towing_mirror_view": 2,
  "qc5_abs_purpose": 2,
  "qc5_abs_not_shorter": 3,
  "qc5_esc_purpose": 3,
  "qc5_systems_not_substitute": 2,
  "qc5_airbag_with_belt": 2,
  "qc5_reversing_camera_limits": 2,
  "qc5_skid_cause": 2,
  "qc5_rear_skid_correct": 3,
  "qc5_front_skid": 3,
  "qc5_smoothness_principle": 1,
  "qc5_main_beam_when": 2,
  "qc5_fog_lights_front": 2,
  "qc5_dirty_lights": 1,
  "qc5_interior_light_night": 2,
  "qc5_dashboard_brightness": 2,
  "qc5_tread_water_job": 2,
  "qc5_wipers_smear": 1,
  "qc5_demist_fastest": 1,
  "qc5_wet_brake_test": 2,
  "qc5_engine_fire": 3,
  "qc5_stuck_in_water": 3,
  "qc5_breakdown_position": 3,
  "qc5_warning_triangle_carry": 2,
  "qc5_fuel_wrong_type": 2,
  "qc5_tyre_pressure_cold": 2,
  "qc5_spare_check": 1,
  "qc5_washer_fluid": 1,
  "qc5_warning_light_colours": 2,
  "qc5_handbrake_ratchet": 2,
  "qc5_seat_adjust_while_driving": 2,
  "qc5_mirror_blindspot_overlap": 3,
  "qc5_wheel_alignment_symptom": 3,
  "qc5_engine_braking_meaning": 2,
  "qc5_child_seat_rear": 2,
  "qc5_documents_carry": 1,
  "qr5_keep_left_pass_right": 1,
  "qr5_overtake_prohibited_where": 2,
  "qr5_overtake_return_gap": 2,
  "qr5_being_overtaken_duty": 1,
  "qr5_zip_merge": 2,
  "qr5_undertake_left": 3,
  "qr5_slow_lane_freeway": 1,
  "qr5_lane_change_signal_check": 1,
  "qr5_bus_pulling_off": 2,
  "qr5_abnormal_load_escort": 2,
  "qr5_scholar_transport": 1,
  "qr5_horse_rider": 2,
  "qr5_road_workers": 1,
  "qr5_disabled_pedestrian": 2,
  "qr5_driver_responsible_condition": 2,
  "qr5_obscured_view_load": 2,
  "qr5_load_secure_duty": 2,
  "qr5_trailer_lights": 2,
  "qr5_tinted_windows": 2,
  "qr5_noise_exhaust": 2,
  "qr5_litter_from_vehicle": 1,
  "qr5_t_junction_priority": 1,
  "qr5_filter_lane_yield": 3,
  "qr5_officer_signal_stop": 1,
  "qr5_pedestrian_signal_flashing": 1,
  "qr5_yield_to_right_circle": 2,
  "qr5_railway_multiple_tracks": 3,
  "qr5_park_corner_visibility": 2,
  "qr5_park_driveway_own": 2,
  "qr5_park_leaving_kerb": 2,
  "qr5_park_wheels_kerb_touch": 1,
  "qr5_fd_spray_from_trucks": 2,
  "qr5_fd_merging_gap_courtesy": 2,
  "qr5_hz_gps_distraction": 2,
  "qr5_hz_eating_driving": 2,
  "qr5_hz_passenger_distraction": 1,
  "qr5_hz_roadworks_speed": 2,
  "qr5_hz_crash_scene_pass": 2,
  "qs4_green_vs_blue_boards": 2,
  "qs4_brown_tourism": 1,
  "qs4_advance_vs_junction": 2,
  "qs4_exit_countdown_markers": 2,
  "qs4_no_through_road_sign": 1,
  "qs4_priority_road_sign": 2,
  "qs4_info_centre": 1,
  "qs4_street_name_position": 2,
  "qs4_danger_plate_chevrons": 2,
  "qs4_overhead_marker": 2,
  "qs4_general_warning_plate": 2,
  "qs4_construction_vehicles": 1,
  "qs4_pedestrian_signal_meaning": 2,
  "qs4_bus_signal_bar": 3,
  "qs4_signal_out_of_order": 1,
  "qs4_lane_control_green_arrow": 2,
  "qs3_priority_road_crossroad": 3,
  "qs3_priority_crossroad_ahead": 3,
  "qs3_side_road_ahead": 2,
  "qs3_staggered_junctions": 3,
  "qs3_height_warning_vs_prohibition": 3,
  "qs3_triangle_vs_ring_general": 2,
  "qs3_narrow_structure": 2,
  "qs3_temp_width_twin": 2,
  "qs3_temp_soft_shoulder": 2,
  "qs3_temp_surface_step": 2,
  "qs3_temp_loose_stones": 1,
  "qs3_drift": 2,
  "qs3_reduced_visibility": 2,
  "qs3_jetty_river": 3,
  "qs3_agricultural_vehicles": 1,
  "qs3_bus_lane_reservation": 3,
  "qs3_reservation_meaning": 3,
  "qs3_parking_reservation": 2,
  "qs3_time_limited_parking": 2,
  "qs3_end_mass_restriction": 2,
  "qs3_end_lane_reservation": 2,
  "qs3_pass_side_shown": 2,
  "qs3_no_hooter": 2,
  "qs3_no_overtaking_goods": 3,
  "qs3_warning_shape_priority": 3,
  "qs3_yellow_temp_reason": 2,
  "qs3_warning_no_obligation": 3,
  "gen-sign-regulatory-006-01-meaning": 1,
  "gen-sign-regulatory-006-01-name": 1,
  "gen-sign-regulatory-006-02-meaning": 1,
  "gen-sign-regulatory-006-02-name": 1,
  "gen-sign-regulatory-006-05-meaning": 1,
  "gen-sign-regulatory-006-05-name": 1,
  "gen-sign-regulatory-007-01-meaning": 3,
  "gen-sign-regulatory-007-01-name": 2,
  "gen-sign-regulatory-007-03-meaning": 1,
  "gen-sign-regulatory-007-03-name": 1,
  "gen-sign-regulatory-007-04-meaning": 1,
  "gen-sign-regulatory-007-04-name": 1,
  "gen-sign-regulatory-008-01-meaning": 1,
  "gen-sign-regulatory-008-01-name": 1,
  "gen-sign-regulatory-008-02-meaning": 1,
  "gen-sign-regulatory-008-02-name": 1,
  "gen-sign-regulatory-008-03-meaning": 1,
  "gen-sign-regulatory-008-03-name": 1,
  "gen-sign-regulatory-008-04-meaning": 3,
  "gen-sign-regulatory-008-04-name": 2,
  "gen-sign-regulatory-009-02-meaning": 3,
  "gen-sign-regulatory-009-02-name": 2,
  "gen-sign-regulatory-009-03-meaning": 1,
  "gen-sign-regulatory-009-03-name": 1,
  "gen-sign-regulatory-009-04-meaning": 3,
  "gen-sign-regulatory-009-04-name": 2,
  "gen-sign-regulatory-009-05-meaning": 3,
  "gen-sign-regulatory-009-05-name": 2,
  "gen-sign-regulatory-009-06-meaning": 3,
  "gen-sign-regulatory-009-07-meaning": 3,
  "gen-sign-regulatory-009-07-name": 2,
  "gen-sign-regulatory-010-02-meaning": 3,
  "gen-sign-regulatory-010-02-name": 2,
  "gen-sign-regulatory-010-04-meaning": 3,
  "gen-sign-regulatory-010-04-name": 2,
  "gen-sign-regulatory-010-05-meaning": 3,
  "gen-sign-regulatory-010-05-name": 2,
  "gen-sign-regulatory-010-06-meaning": 3,
  "gen-sign-regulatory-010-06-name": 2,
  "gen-sign-regulatory-010-07-meaning": 3,
  "gen-sign-regulatory-010-07-name": 2,
  "gen-sign-regulatory-011-01-name": 1,
  "gen-sign-regulatory-011-02-meaning": 1,
  "gen-sign-regulatory-011-02-name": 1,
  "gen-sign-regulatory-011-03-meaning": 3,
  "gen-sign-regulatory-011-03-name": 2,
  "gen-sign-regulatory-011-04-meaning": 3,
  "gen-sign-regulatory-011-04-name": 2,
  "gen-sign-regulatory-011-05-meaning": 1,
  "gen-sign-regulatory-011-05-name": 1,
  "gen-sign-regulatory-011-07-name": 1,
  "gen-sign-regulatory-012-01-meaning": 1,
  "gen-sign-regulatory-012-01-name": 1,
  "gen-sign-regulatory-012-02-meaning": 3,
  "gen-sign-regulatory-012-02-name": 2,
  "gen-sign-regulatory-012-03-meaning": 3,
  "gen-sign-regulatory-012-03-name": 2,
  "gen-sign-regulatory-012-04-meaning": 3,
  "gen-sign-regulatory-012-05-meaning": 3,
  "gen-sign-regulatory-012-05-name": 2,
  "gen-sign-regulatory-012-06-meaning": 3,
  "gen-sign-regulatory-012-06-name": 2,
  "gen-sign-regulatory-012-07-meaning": 3,
  "gen-sign-regulatory-012-07-name": 2,
  "gen-sign-regulatory-013-01-meaning": 3,
  "gen-sign-regulatory-013-01-name": 2,
  "gen-sign-regulatory-013-02-meaning": 3,
  "gen-sign-regulatory-013-03-meaning": 3,
  "gen-sign-regulatory-013-04-meaning": 3,
  "gen-sign-regulatory-013-05-meaning": 3,
  "gen-sign-regulatory-013-06-meaning": 3,
  "gen-sign-regulatory-013-06-name": 2,
  "gen-sign-regulatory-013-07-meaning": 3,
  "gen-sign-regulatory-013-07-name": 2,
  "gen-sign-regulatory-014-01-meaning": 3,
  "gen-sign-regulatory-014-01-name": 2,
  "gen-sign-regulatory-014-02-meaning": 3,
  "gen-sign-regulatory-014-02-name": 2,
  "gen-sign-regulatory-014-03-meaning": 3,
  "gen-sign-regulatory-014-03-name": 2,
  "gen-sign-regulatory-014-04-meaning": 3,
  "gen-sign-regulatory-014-04-name": 2,
  "gen-sign-regulatory-014-05-meaning": 3,
  "gen-sign-regulatory-014-05-name": 2,
  "gen-sign-regulatory-014-06-meaning": 3,
  "gen-sign-regulatory-014-06-name": 2,
  "gen-sign-regulatory-014-07-meaning": 3,
  "gen-sign-regulatory-014-07-name": 2,
  "gen-sign-regulatory-017-02-meaning": 3,
  "gen-sign-regulatory-017-02-name": 2,
  "gen-sign-regulatory-017-03-meaning": 3,
  "gen-sign-regulatory-017-03-name": 2,
  "gen-sign-regulatory-017-04-meaning": 3,
  "gen-sign-regulatory-017-04-name": 2,
  "gen-sign-regulatory-017-05-meaning": 3,
  "gen-sign-regulatory-017-05-name": 2,
  "gen-sign-regulatory-017-06-meaning": 3,
  "gen-sign-regulatory-017-06-name": 2,
  "gen-sign-regulatory-017-07-meaning": 3,
  "gen-sign-regulatory-017-07-name": 2,
  "gen-sign-regulatory-019-04-meaning": 3,
  "gen-sign-regulatory-020-03-meaning": 3,
  "gen-sign-regulatory-020-04-meaning": 3,
  "gen-sign-regulatory-021-02-meaning": 3,
  "gen-sign-regulatory-021-03-meaning": 3,
  "gen-sign-regulatory-022-01-name": 1,
  "gen-sign-regulatory-022-03-meaning": 1,
  "gen-sign-regulatory-022-03-name": 1,
  "gen-sign-regulatory-022-04-meaning": 1,
  "gen-sign-regulatory-022-04-name": 1,
  "gen-sign-warning-027-01-meaning": 3,
  "gen-sign-warning-027-01-name": 2,
  "gen-sign-warning-027-02-meaning": 1,
  "gen-sign-warning-027-02-name": 1,
  "gen-sign-warning-027-03-meaning": 3,
  "gen-sign-warning-027-03-name": 2,
  "gen-sign-warning-027-04-meaning": 1,
  "gen-sign-warning-027-04-name": 1,
  "gen-sign-warning-027-05-meaning": 1,
  "gen-sign-warning-027-05-name": 1,
  "gen-sign-warning-027-06-name": 2,
  "gen-sign-warning-028-01-meaning": 3,
  "gen-sign-warning-028-01-name": 2,
  "gen-sign-warning-028-02-meaning": 3,
  "gen-sign-warning-028-02-name": 2,
  "gen-sign-warning-028-03-meaning": 3,
  "gen-sign-warning-028-03-name": 2,
  "gen-sign-warning-028-04-meaning": 3,
  "gen-sign-warning-028-04-name": 2,
  "gen-sign-warning-028-05-meaning": 3,
  "gen-sign-warning-028-05-name": 2,
  "gen-sign-warning-028-06-meaning": 3,
  "gen-sign-warning-028-06-name": 2,
  "gen-sign-warning-028-07-meaning": 3,
  "gen-sign-warning-028-07-name": 2,
  "gen-sign-warning-029-01-meaning": 3,
  "gen-sign-warning-029-01-name": 2,
  "gen-sign-warning-029-02-meaning": 3,
  "gen-sign-warning-029-02-name": 2,
  "gen-sign-warning-029-03-meaning": 3,
  "gen-sign-warning-029-03-name": 2,
  "gen-sign-warning-029-04-meaning": 3,
  "gen-sign-warning-029-04-name": 2,
  "gen-sign-warning-029-05-meaning": 3,
  "gen-sign-warning-029-05-name": 2,
  "gen-sign-warning-029-06-meaning": 3,
  "gen-sign-warning-029-06-name": 2,
  "gen-sign-warning-029-07-meaning": 3,
  "gen-sign-warning-029-07-name": 2,
  "gen-sign-warning-030-01-meaning": 3,
  "gen-sign-warning-030-01-name": 2,
  "gen-sign-warning-030-02-meaning": 3,
  "gen-sign-warning-030-02-name": 2,
  "gen-sign-warning-030-03-meaning": 3,
  "gen-sign-warning-030-03-name": 2,
  "gen-sign-warning-030-04-meaning": 3,
  "gen-sign-warning-030-05-meaning": 3,
  "gen-sign-warning-030-05-name": 2,
  "gen-sign-warning-031-01-meaning": 3,
  "gen-sign-warning-031-01-name": 2,
  "gen-sign-warning-031-02-meaning": 3,
  "gen-sign-warning-031-02-name": 2,
  "gen-sign-warning-031-03-meaning": 3,
  "gen-sign-warning-031-03-name": 2,
  "gen-sign-warning-031-04-meaning": 3,
  "gen-sign-warning-031-04-name": 2,
  "gen-sign-warning-031-05-meaning": 3,
  "gen-sign-warning-031-05-name": 2,
  "gen-sign-warning-031-06-meaning": 3,
  "gen-sign-warning-031-06-name": 2,
  "gen-sign-warning-035-02-meaning": 3,
  "gen-sign-warning-035-02-name": 2,
  "gen-sign-warning-035-03-meaning": 3,
  "gen-sign-warning-035-03-name": 2,
  "gen-sign-warning-035-06-name": 2,
  "gen-sign-warning-035-07-name": 2,
  "gen-sign-warning-037-01-meaning": 1,
  "gen-sign-warning-037-01-name": 1,
  "gen-sign-warning-037-02-name": 1,
  "gen-sign-warning-037-03-name": 1,
  "gen-sign-warning-037-04-name": 1,
  "gen-sign-warning-038-07-name": 2,
  "gen-sign-warning-039-03-meaning": 3,
  "gen-sign-warning-039-03-name": 2,
  "gen-sign-warning-040-01-meaning": 3,
  "gen-sign-warning-040-01-name": 2,
  "gen-sign-warning-040-02-meaning": 3,
  "gen-sign-warning-040-03-meaning": 3,
  "gen-sign-warning-040-04-meaning": 3,
  "gen-sign-warning-040-04-name": 2,
  "gen-sign-warning-040-05-meaning": 3,
  "gen-sign-warning-040-06-meaning": 3,
  "gen-sign-warning-040-07-meaning": 1,
  "gen-sign-warning-040-07-name": 1,
  "gen-sign-information-043-01-meaning": 3,
  "gen-sign-information-043-01-name": 2,
  "gen-sign-information-043-02-meaning": 3,
  "gen-sign-information-043-03-meaning": 3,
  "gen-sign-information-043-03-name": 2,
  "gen-sign-information-043-04-meaning": 3,
  "gen-sign-information-043-05-meaning": 3,
  "gen-sign-information-043-05-name": 2,
  "gen-sign-information-044-03-meaning": 3,
  "gen-sign-information-044-03-name": 2,
  "gen-sign-information-044-04-meaning": 3,
  "gen-sign-information-044-04-name": 2,
};

export const FLASHCARD_META: ContentMeta[] = [
  { id: "fc_stop", categoryId: "signs" },
  { id: "fc_yield", categoryId: "signs" },
  { id: "fc_yield_ped", categoryId: "signs" },
  { id: "fc_ped_priority", categoryId: "signs" },
  { id: "fc_no_entry", categoryId: "signs" },
  { id: "fc_one_way", categoryId: "signs" },
  { id: "fc_no_left", categoryId: "signs" },
  { id: "fc_no_right", categoryId: "signs" },
  { id: "fc_no_uturn", categoryId: "signs" },
  { id: "fc_no_parking", categoryId: "signs" },
  { id: "fc_no_overtaking", categoryId: "signs" },
  { id: "fc_speed", categoryId: "signs" },
  { id: "fc_robot_red", categoryId: "signs" },
  { id: "fc_robot_amber", categoryId: "signs" },
  { id: "fc_robot_green", categoryId: "signs" },
  { id: "fc_ped_warn", categoryId: "signs" },
  { id: "fc_children", categoryId: "signs" },
  { id: "fc_railway", categoryId: "signs" },
  { id: "fc_steep_down", categoryId: "signs" },
  { id: "fc_triangle", categoryId: "signs" },
  { id: "fc_regulatory", categoryId: "signs" },
  { id: "fc_blue_signs", categoryId: "signs" },
  { id: "fc_solid_line", categoryId: "signs" },
  { id: "fc_yellow_edge", categoryId: "signs" },
  { id: "fc_flashing_red", categoryId: "signs" },
  { id: "fc_speed_limits", categoryId: "rules" },
  { id: "fc_alcohol", categoryId: "rules" },
  { id: "fc_keep_left", categoryId: "rules" },
  { id: "fc_divided", categoryId: "rules" },
  { id: "fc_triangle_distance", categoryId: "rules" },
  { id: "fc_tread", categoryId: "rules" },
  { id: "fc_right_arm", categoryId: "rules" },
  { id: "fc_lights_on", categoryId: "rules" },
  { id: "fc_beams", categoryId: "rules" },
  { id: "fc_cellphone", categoryId: "rules" },
  { id: "fc_seatbelt", categoryId: "rules" },
  { id: "fc_ped_rights", categoryId: "rules" },
  { id: "fc_being_overtaken", categoryId: "rules" },
  { id: "fc_freeway_who", categoryId: "rules" },
  { id: "fc_clutch", categoryId: "controls" },
  { id: "fc_accelerator", categoryId: "controls" },
  { id: "fc_footbrake", categoryId: "controls" },
  { id: "fc_handbrake_start", categoryId: "controls" },
  { id: "fc_handbrake_motion", categoryId: "controls" },
  { id: "fc_clutch_control", categoryId: "controls" },
  { id: "fc_overheat", categoryId: "controls" },
  { id: "fc_dip", categoryId: "controls" },
  { id: "fc_mirror_freq", categoryId: "controls" },
  { id: "fc_cancel_signal", categoryId: "controls" },
  { id: "fc_4way", categoryId: "intersections" },
  { id: "fc_circle", categoryId: "intersections" },
  { id: "fc_dead_robot", categoryId: "intersections" },
  { id: "fc_right_turn", categoryId: "intersections" },
  { id: "fc_green_arrow", categoryId: "intersections" },
  { id: "fc_t_junction", categoryId: "intersections" },
  { id: "fc_box_clear", categoryId: "intersections" },
  { id: "fc_turn_ped", categoryId: "intersections" },
  { id: "fc_park_crossing", categoryId: "parking" },
  { id: "fc_park_intersection", categoryId: "parking" },
  { id: "fc_park_downhill", categoryId: "parking" },
  { id: "fc_park_uphill", categoryId: "parking" },
  { id: "fc_no_stopping", categoryId: "parking" },
  { id: "fc_park_bay", categoryId: "parking" },
  { id: "fc_park_hydrant", categoryId: "parking" },
  { id: "fc_two_sec", categoryId: "following_distance" },
  { id: "fc_wet_gap", categoryId: "following_distance" },
  { id: "fc_truck_gap", categoryId: "following_distance" },
  { id: "fc_brake_square", categoryId: "following_distance" },
  { id: "fc_stopping_parts", categoryId: "following_distance" },
  { id: "fc_night_gap", categoryId: "following_distance" },
  { id: "fc_blind_spot", categoryId: "hazard_awareness" },
  { id: "fc_aquaplane", categoryId: "hazard_awareness" },
  { id: "fc_fatigue", categoryId: "hazard_awareness" },
  { id: "fc_scan", categoryId: "hazard_awareness" },
  { id: "fc_ball", categoryId: "hazard_awareness" },
  { id: "fc_skid", categoryId: "hazard_awareness" },
  { id: "vf_mc_front_lever", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_rear_pedal", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_clutch", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_throttle", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_gear_pattern", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_kill_switch", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_front_brake_lean", categoryId: "controls", codes: ["A1","A"] },
  { id: "vf_mc_helmet", categoryId: "rules", codes: ["A1","A"] },
  { id: "vf_mc_a1_limit", categoryId: "rules", codes: ["A1","A"] },
  { id: "vf_mc_pillion", categoryId: "rules", codes: ["A1","A"] },
  { id: "vf_mc_lane_filtering", categoryId: "rules", codes: ["A1","A"] },
  { id: "vf_mc_prohibition_sign", categoryId: "signs", codes: ["A1","A"] },
  { id: "vf_mc_class_speed_sign", categoryId: "signs", codes: ["A1","A"] },
  { id: "vf_mc_surface_hazards", categoryId: "hazard_awareness", codes: ["A1","A"] },
  { id: "vf_mc_turbulence", categoryId: "hazard_awareness", codes: ["A1","A"] },
  { id: "vf_hv_air_pressure", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_spring_brake", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_treadle", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_diff_lock", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_retarder", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_fifth_wheel", categoryId: "controls", codes: ["14"] },
  { id: "vf_hv_tug_test", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_air_lines", categoryId: "controls", codes: ["14"] },
  { id: "vf_hv_landing_gear", categoryId: "controls", codes: ["10","14"] },
  { id: "vf_hv_trailer_electrics", categoryId: "controls", codes: ["14"] },
  { id: "vf_hv_jackknife", categoryId: "hazard_awareness", codes: ["10","14"] },
  { id: "vf_hv_stopping_distance", categoryId: "hazard_awareness", codes: ["14"] },
  { id: "vf_hv_following_distance", categoryId: "following_distance", codes: ["10","14"] },
  { id: "vf_hv_mass_sign", categoryId: "signs", codes: ["10","14"] },
  { id: "vf_hv_height_sign", categoryId: "signs", codes: ["10","14"] },
  { id: "vf_car_auto_selector", categoryId: "controls", codes: ["8"] },
  { id: "vf_car_epb", categoryId: "controls", codes: ["8"] },
  { id: "fc2_one_way_right", categoryId: "signs" },
  { id: "fc2_steep_ascent", categoryId: "signs" },
  { id: "fc2_temp_signs", categoryId: "signs" },
  { id: "fc2_green_boards", categoryId: "signs" },
  { id: "fc2_brown_signs", categoryId: "signs" },
  { id: "fc2_blue_command", categoryId: "signs" },
  { id: "fc2_stop_yield_lines", categoryId: "signs" },
  { id: "fc2_painted_island", categoryId: "signs" },
  { id: "fc2_lane_arrows", categoryId: "signs" },
  { id: "fc2_school_patrol", categoryId: "signs" },
  { id: "fc2_rumble", categoryId: "signs" },
  { id: "fc2_clearance", categoryId: "signs" },
  { id: "fc2_wild_animals", categoryId: "signs" },
  { id: "fc2_accident_24h", categoryId: "rules" },
  { id: "fc2_tow_rope", categoryId: "rules" },
  { id: "fc2_caravan_people", categoryId: "rules" },
  { id: "fc2_load_rear", categoryId: "rules" },
  { id: "fc2_door", categoryId: "rules" },
  { id: "fc2_reversing", categoryId: "rules" },
  { id: "fc2_coasting", categoryId: "rules" },
  { id: "fc2_hooter", categoryId: "rules" },
  { id: "fc2_night_parked", categoryId: "rules" },
  { id: "fc2_cyclist_1m", categoryId: "rules" },
  { id: "fc2_ped_freeway", categoryId: "rules" },
  { id: "fc2_officer", categoryId: "rules" },
  { id: "fc2_learner_codes", categoryId: "rules" },
  { id: "fc2_prof_limit", categoryId: "rules" },
  { id: "fc2_bus_100", categoryId: "rules" },
  { id: "fc2_hazard_use", categoryId: "controls" },
  { id: "fc2_oil_light", categoryId: "controls" },
  { id: "fc2_battery_light", categoryId: "controls" },
  { id: "fc2_headrest", categoryId: "controls" },
  { id: "fc2_ignition_moving", categoryId: "controls" },
  { id: "fc2_dry_steer", categoryId: "controls" },
  { id: "fc2_uncontrolled", categoryId: "intersections" },
  { id: "fc2_multilane_circle", categoryId: "intersections" },
  { id: "fc2_red_arrow", categoryId: "intersections" },
  { id: "fc2_left_turn_pos", categoryId: "intersections" },
  { id: "fc2_rail_two_trains", categoryId: "intersections" },
  { id: "fc2_park_9m_road", categoryId: "parking" },
  { id: "fc2_park_direction", categoryId: "parking" },
  { id: "fc2_park_kerb", categoryId: "parking" },
  { id: "fc2_park_bus_stop", categoryId: "parking" },
  { id: "fc2_double_park", categoryId: "parking" },
  { id: "fc2_hill_gap", categoryId: "following_distance" },
  { id: "fc2_gravel_gap", categoryId: "following_distance" },
  { id: "fc2_reaction_28m", categoryId: "following_distance" },
  { id: "fc2_taxi_gap", categoryId: "following_distance" },
  { id: "fc2_night_peds", categoryId: "hazard_awareness" },
  { id: "fc2_pothole", categoryId: "hazard_awareness" },
  { id: "fc2_blowout", categoryId: "hazard_awareness" },
  { id: "fc2_glare", categoryId: "hazard_awareness" },
  { id: "fc2_first_rain", categoryId: "hazard_awareness" },
  { id: "fc2_fog", categoryId: "hazard_awareness" },
  { id: "fc2_car_child", categoryId: "rules", codes: ["8"] },
  { id: "fc2_car_airbag", categoryId: "rules", codes: ["8"] },
  { id: "fc2_car_cruise", categoryId: "hazard_awareness", codes: ["8"] },
  { id: "fc2_mc_headlight", categoryId: "rules", codes: ["A"] },
  { id: "fc2_mc_learner_pillion", categoryId: "rules", codes: ["A"] },
  { id: "fc2_mc_gear", categoryId: "hazard_awareness", codes: ["A"] },
  { id: "fc2_mc_chain", categoryId: "controls", codes: ["A"] },
  { id: "fc2_mc_paint", categoryId: "hazard_awareness", codes: ["A"] },
  { id: "fc2_mc_eyes", categoryId: "hazard_awareness", codes: ["A"] },
  { id: "fc2_hv_arrester", categoryId: "hazard_awareness", codes: ["14"] },
  { id: "fc2_hv_descent", categoryId: "controls", codes: ["14"] },
  { id: "fc2_hv_blind", categoryId: "hazard_awareness", codes: ["14"] },
  { id: "fc2_hv_tail_swing", categoryId: "hazard_awareness", codes: ["14"] },
  { id: "fc2_hv_height", categoryId: "rules", codes: ["14"] },
  { id: "fc2_hv_load_recheck", categoryId: "rules", codes: ["14"] },
  { id: "fc3_park_450", categoryId: "parking" },
  { id: "fc3_park_5m", categoryId: "parking" },
  { id: "fc3_park_two_way", categoryId: "parking" },
  { id: "fc3_park_unattended", categoryId: "parking" },
  { id: "fc3_park_downhill", categoryId: "parking" },
  { id: "fc3_park_yellow_edge", categoryId: "parking" },
  { id: "fc3_fd_count", categoryId: "following_distance" },
  { id: "fc3_fd_wet4", categoryId: "following_distance" },
  { id: "fc3_fd_stopping", categoryId: "following_distance" },
  { id: "fc3_fd_square", categoryId: "following_distance" },
  { id: "fc3_fd_queue", categoryId: "following_distance" },
  { id: "fc3_int_4way", categoryId: "intersections" },
  { id: "fc3_int_dead_robot", categoryId: "intersections" },
  { id: "fc3_int_right_turn", categoryId: "intersections" },
  { id: "fc3_int_circle_vs_mini", categoryId: "intersections" },
  { id: "fc3_int_blocked_box", categoryId: "intersections" },
  { id: "fc3_rule_speeds", categoryId: "rules" },
  { id: "fc3_rule_bac", categoryId: "rules" },
  { id: "fc3_rule_demerits", categoryId: "rules" },
  { id: "fc3_rule_ages", categoryId: "rules" },
  { id: "vxf_mc_learner_alone", categoryId: "rules", codes: ["A1","A"] },
  { id: "vxf_mc_helmets", categoryId: "rules", codes: ["A1","A"] },
  { id: "vxf_mc_headlight", categoryId: "rules", codes: ["A1","A"] },
  { id: "vxf_mc_a1", categoryId: "rules", codes: ["A1","A"] },
  { id: "vxf_mc_lifesaver", categoryId: "hazard_awareness", codes: ["A1","A"] },
  { id: "vxf_mc_wet_surfaces", categoryId: "hazard_awareness", codes: ["A1","A"] },
  { id: "vxf_hv_80", categoryId: "rules", codes: ["10","14"] },
  { id: "vxf_hv_code10", categoryId: "rules", codes: ["10","14"] },
  { id: "vxf_hv_descent", categoryId: "controls", codes: ["10","14"] },
  { id: "vxf_hv_air", categoryId: "controls", codes: ["10","14"] },
  { id: "vxf_hv_left_mirror", categoryId: "hazard_awareness", codes: ["10","14"] },
  { id: "vxf_hv_3sec", categoryId: "following_distance", codes: ["10","14"] },
  { id: "fc4_grammar_circle_red", categoryId: "signs" },
  { id: "fc4_grammar_circle_blue", categoryId: "signs" },
  { id: "fc4_grammar_triangle", categoryId: "signs" },
  { id: "fc4_grammar_yellow_bg", categoryId: "signs" },
  { id: "fc4_grammar_shapes", categoryId: "signs" },
  { id: "fc4_grammar_derestrict", categoryId: "signs" },
  { id: "fc4_headlights", categoryId: "signs" },
  { id: "fc4_pass_side", categoryId: "signs" },
  { id: "fc4_circle_cmd", categoryId: "signs" },
  { id: "fc4_no_left_int", categoryId: "signs" },
  { id: "fc4_no_ot_trucks", categoryId: "signs" },
  { id: "fc4_no_hooter", categoryId: "signs" },
  { id: "fc4_reserved_bus", categoryId: "signs" },
  { id: "fc4_no_stopping", categoryId: "signs" },
  { id: "fc4_speed_blue", categoryId: "signs" },
  { id: "fc4_flashing_red", categoryId: "signs" },
  { id: "fc4_flashing_amber", categoryId: "signs" },
  { id: "fc4_green_arrow", categoryId: "signs" },
  { id: "fc4_robot_amber", categoryId: "signs" },
  { id: "fc4_children_sign", categoryId: "signs" },
  { id: "fc4_railway_sign", categoryId: "signs" },
  { id: "fc4_descent", categoryId: "signs" },
  { id: "fc4_green_boards", categoryId: "signs" },
  { id: "fc4_brown", categoryId: "signs" },
  { id: "fc4_mark_across", categoryId: "signs" },
  { id: "fc4_mark_centre", categoryId: "signs" },
  { id: "fc4_mark_combo", categoryId: "signs" },
  { id: "fc4_mark_island", categoryId: "signs" },
  { id: "fc4_mark_arrows", categoryId: "signs" },
  { id: "fc4_mark_zebra", categoryId: "signs" },
  { id: "fc4_mark_yellow", categoryId: "signs" },
  { id: "fc5_freeway_banned", categoryId: "rules" },
  { id: "fc5_freeway_missed_exit", categoryId: "rules" },
  { id: "fc5_lights_rule", categoryId: "rules" },
  { id: "fc5_dip_rule", categoryId: "rules" },
  { id: "fc5_belts_driver", categoryId: "rules" },
  { id: "fc5_infant_seat", categoryId: "rules" },
  { id: "fc5_overtake_left", categoryId: "rules" },
  { id: "fc5_being_overtaken", categoryId: "rules" },
  { id: "fc5_overtake_test", categoryId: "rules" },
  { id: "fc5_hierarchy", categoryId: "rules" },
  { id: "fc5_emergency", categoryId: "rules" },
  { id: "fc5_herder", categoryId: "rules" },
  { id: "fc5_coasting", categoryId: "rules" },
  { id: "fc5_reversing", categoryId: "rules" },
  { id: "fc5_hooter", categoryId: "rules" },
  { id: "fc5_windscreen", categoryId: "rules" },
  { id: "fc5_hand_right", categoryId: "rules" },
  { id: "fc5_hand_slow", categoryId: "rules" },
  { id: "fc5_signal_early", categoryId: "rules" },
  { id: "fc5_crash_scene", categoryId: "rules" },
  { id: "fc6_double_solid", categoryId: "signs" },
  { id: "fc6_barrier_legal", categoryId: "signs" },
  { id: "fc6_white_edge", categoryId: "signs" },
  { id: "fc6_yellow_shoulder", categoryId: "signs" },
  { id: "fc6_studs_colours", categoryId: "signs" },
  { id: "fc6_studs_red", categoryId: "signs" },
  { id: "fc6_box_junction", categoryId: "signs" },
  { id: "fc6_keep_clear", categoryId: "signs" },
  { id: "fc6_ped_setback", categoryId: "signs" },
  { id: "fc6_lane_reduction", categoryId: "signs" },
  { id: "fc6_island_border", categoryId: "signs" },
  { id: "fc6_speed_hump_mark", categoryId: "signs" },
  { id: "fc6_temp_force", categoryId: "signs" },
  { id: "fc6_temp_why", categoryId: "signs" },
  { id: "fc6_temp_flag", categoryId: "signs" },
  { id: "fc6_temp_speed", categoryId: "signs" },
  { id: "fc6_temp_cones", categoryId: "signs" },
  { id: "fc6_temp_detour", categoryId: "signs" },
  { id: "fc6_temp_priority", categoryId: "signs" },
  { id: "fc6_temp_until_lifted", categoryId: "signs" },
  { id: "fc7_given_not_taken", categoryId: "intersections" },
  { id: "fc7_stop_empty", categoryId: "intersections" },
  { id: "fc7_stop_vs_yield_junction", categoryId: "intersections" },
  { id: "fc7_uncontrolled", categoryId: "intersections" },
  { id: "fc7_minor_major", categoryId: "intersections" },
  { id: "fc7_stale_green", categoryId: "intersections" },
  { id: "fc7_right_no_arrow", categoryId: "intersections" },
  { id: "fc7_green_still_yield", categoryId: "intersections" },
  { id: "fc7_left_cyclist", categoryId: "intersections" },
  { id: "fc7_twin_right", categoryId: "intersections" },
  { id: "fc7_sequence", categoryId: "intersections" },
  { id: "fc7_right_yield_oncoming", categoryId: "intersections" },
  { id: "fc7_left_position", categoryId: "intersections" },
  { id: "fc7_circle_signal", categoryId: "intersections" },
  { id: "fc7_circle_no_stop", categoryId: "intersections" },
  { id: "fc7_circle_gap", categoryId: "intersections" },
  { id: "fc7_zip", categoryId: "intersections" },
  { id: "fc7_blind", categoryId: "intersections" },
  { id: "fc7_ped_crossing", categoryId: "intersections" },
  { id: "fc7_emergency_green", categoryId: "intersections" },
  { id: "fc8_two_parts", categoryId: "controls" },
  { id: "fc8_yard_manoeuvres", categoryId: "controls" },
  { id: "fc8_incline_fail", categoryId: "controls" },
  { id: "fc8_pole_contact", categoryId: "controls" },
  { id: "fc8_alley_dock", categoryId: "controls" },
  { id: "fc8_observe_every", categoryId: "controls" },
  { id: "fc8_moving_off_look", categoryId: "controls" },
  { id: "fc8_reverse_look", categoryId: "controls" },
  { id: "fc8_steer_method", categoryId: "controls" },
  { id: "fc8_wheel_recovery", categoryId: "controls" },
  { id: "fc8_hands_on", categoryId: "controls" },
  { id: "fc8_cockpit", categoryId: "controls" },
  { id: "fc8_pretrip_ext", categoryId: "controls" },
  { id: "fc8_start_neutral", categoryId: "controls" },
  { id: "fc8_ride_clutch", categoryId: "controls" },
  { id: "fc8_reverse_stat", categoryId: "controls" },
  { id: "fc8_right_gear", categoryId: "controls" },
  { id: "fc8_cover_brake", categoryId: "controls" },
  { id: "fc8_stall", categoryId: "controls" },
  { id: "fc8_progressive", categoryId: "controls" },
  { id: "fc9_scan", categoryId: "hazard_awareness" },
  { id: "fc9_cushion", categoryId: "hazard_awareness" },
  { id: "fc9_crosswind", categoryId: "hazard_awareness" },
  { id: "fc9_smoke", categoryId: "hazard_awareness" },
  { id: "fc9_stray", categoryId: "hazard_awareness" },
  { id: "fc9_rage", categoryId: "hazard_awareness" },
  { id: "fc9_meds", categoryId: "hazard_awareness" },
  { id: "fc9_bus", categoryId: "hazard_awareness" },
  { id: "fc9_debris", categoryId: "hazard_awareness" },
  { id: "fc9_hill_no_kerb", categoryId: "parking" },
  { id: "fc9_secure_steep", categoryId: "parking" },
  { id: "fc9_leave_bay", categoryId: "parking" },
  { id: "fc9_door", categoryId: "parking" },
  { id: "fc9_pavement", categoryId: "parking" },
  { id: "fc9_corner", categoryId: "parking" },
  { id: "fc9_angle_out", categoryId: "parking" },
  { id: "fc9_towing", categoryId: "following_distance" },
  { id: "fc9_erratic", categoryId: "following_distance" },
  { id: "fc9_loaded", categoryId: "following_distance" },
  { id: "fc9_why_seconds", categoryId: "following_distance" },
  { id: "fc9_helps_behind", categoryId: "following_distance" },
  { id: "fc9_new_driver", categoryId: "following_distance" },
  { id: "fc10_mc_countersteer", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_position", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_corner", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_brakes", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_smidsy", categoryId: "hazard_awareness", codes: ["A"] },
  { id: "fc10_mc_gravel", categoryId: "hazard_awareness", codes: ["A"] },
  { id: "fc10_mc_preride", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_stop", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_look", categoryId: "controls", codes: ["A"] },
  { id: "fc10_mc_pillion", categoryId: "controls", codes: ["A"] },
  { id: "fc10_hv_low_air", categoryId: "controls", codes: ["10","14"] },
  { id: "fc10_hv_rollover", categoryId: "hazard_awareness", codes: ["10","14"] },
  { id: "fc10_hv_offtrack", categoryId: "hazard_awareness", codes: ["14"] },
  { id: "fc10_hv_coupling", categoryId: "controls", codes: ["14"] },
  { id: "fc10_hv_reverse", categoryId: "controls", codes: ["14"] },
  { id: "fc10_hv_axle", categoryId: "controls", codes: ["10","14"] },
  { id: "fc10_hv_overload", categoryId: "hazard_awareness", codes: ["10","14"] },
  { id: "fc10_hv_dg", categoryId: "rules", codes: ["10","14"] },
  { id: "fc10_hv_dual", categoryId: "controls", codes: ["10","14"] },
  { id: "fc10_hv_uncouple", categoryId: "controls", codes: ["14"] },
  { id: "fc10_hv_fade", categoryId: "hazard_awareness", codes: ["10","14"] },
  { id: "fc11_park_bridge", categoryId: "parking" },
  { id: "fc11_park_freeway", categoryId: "parking" },
  { id: "fc11_park_driveway", categoryId: "parking" },
  { id: "fc11_park_disabled_bay", categoryId: "parking" },
  { id: "fc11_park_night_rural", categoryId: "parking" },
  { id: "fc11_park_reverse_bay", categoryId: "parking" },
  { id: "fc11_fd_night_range", categoryId: "following_distance" },
  { id: "fc11_fd_following_bike", categoryId: "following_distance" },
  { id: "fc11_fd_cut_in", categoryId: "following_distance" },
  { id: "fc11_fd_queue", categoryId: "following_distance" },
  { id: "fc11_fd_sides", categoryId: "following_distance" },
  { id: "fc11_int_amber", categoryId: "intersections" },
  { id: "fc11_int_second_train", categoryId: "intersections" },
  { id: "fc11_int_slipway", categoryId: "intersections" },
  { id: "fc11_int_scholar_patrol", categoryId: "intersections" },
  { id: "fc11_haz_low_sun", categoryId: "hazard_awareness" },
  { id: "fc11_haz_brake_fail", categoryId: "hazard_awareness" },
  { id: "fc11_haz_freeway_breakdown", categoryId: "hazard_awareness" },
  { id: "fc11_haz_oncoming_overtaker", categoryId: "hazard_awareness" },
  { id: "fca_start_date", categoryId: "rules" },
  { id: "fca_what_is", categoryId: "rules" },
  { id: "fca_learner_threshold", categoryId: "rules" },
  { id: "fca_licensed_threshold", categoryId: "rules" },
  { id: "fca_excess_suspension", categoryId: "rules" },
  { id: "fca_expiry", categoryId: "rules" },
  { id: "fca_paying_fine", categoryId: "rules" },
  { id: "fca_no_licence", categoryId: "rules" },
  { id: "fca_stop_line", categoryId: "rules" },
  { id: "fca_cancellation", categoryId: "rules" },
  { id: "fca_when_added", categoryId: "rules" },
  { id: "fca_meaning", categoryId: "rules" },
  { id: "fcd_q_sign_flashing_red", categoryId: "signs" },
  { id: "fcd_q_sign_ped_crossing", categoryId: "signs" },
  { id: "fcd_q_sign_cyclists", categoryId: "signs" },
  { id: "fcd_q_sign_gate_boom", categoryId: "signs" },
  { id: "fcd_q_sign_reg_shape", categoryId: "signs" },
  { id: "fcd_q_sign_default_urban", categoryId: "signs" },
  { id: "fcd_q_sign_default_rural", categoryId: "signs" },
  { id: "fcd_q_sign_broken_white", categoryId: "signs" },
  { id: "fcd_q_sign_solid_white", categoryId: "signs" },
  { id: "fcd_q_sign_yellow_line", categoryId: "signs" },
  { id: "fcd_q_sign_red_line_kerb", categoryId: "signs" },
  { id: "fcd_q_sign_box_junction", categoryId: "signs" },
  { id: "fcd_q_sign_green_route", categoryId: "signs" },
  { id: "fcd_q_sign_de_restriction", categoryId: "signs" },
  { id: "fcd_q_sign_freeway_start", categoryId: "signs" },
  { id: "fcd_q_ctrl_clutch", categoryId: "controls" },
  { id: "fcd_q_ctrl_accelerator", categoryId: "controls" },
  { id: "fcd_q_ctrl_footbrake", categoryId: "controls" },
  { id: "fcd_q_ctrl_handbrake", categoryId: "controls" },
  { id: "fcd_q_ctrl_handbrake_motion", categoryId: "controls" },
  { id: "fcd_q_ctrl_clutch_control", categoryId: "controls" },
  { id: "fcd_q_ctrl_temp", categoryId: "controls" },
  { id: "fcd_q_ctrl_abs", categoryId: "controls" },
  { id: "fcd_q_ctrl_mirrors", categoryId: "controls" },
  { id: "fcd_q_ctrl_steering", categoryId: "controls" },
  { id: "fcd_q_ctrl_headlights", categoryId: "controls" },
  { id: "fcd_q_ctrl_indicator", categoryId: "controls" },
  { id: "fcd_q_ctrl_engine_braking", categoryId: "controls" },
  { id: "fcd_q_ctrl_fuel_warning", categoryId: "controls" },
  { id: "fcd_q_rules_freeway_speed", categoryId: "rules" },
  { id: "fcd_q_rules_alcohol", categoryId: "rules" },
  { id: "fcd_q_rules_seatbelt", categoryId: "rules" },
  { id: "fcd_q_rules_hand_signal", categoryId: "rules" },
  { id: "fcd_q_rules_hand_freeway", categoryId: "rules" },
  { id: "fcd_q_rules_keep_left", categoryId: "rules" },
  { id: "fcd_q_rules_divided_solid", categoryId: "rules" },
  { id: "fcd_q_rules_overtake_blind", categoryId: "rules" },
  { id: "fcd_q_rules_overtake_left", categoryId: "rules" },
  { id: "fcd_q_rules_being_overtaken", categoryId: "rules" },
  { id: "fcd_q_rules_turn_right_position", categoryId: "rules" },
  { id: "fcd_q_rules_emergency_triangle", categoryId: "rules" },
  { id: "fcd_q_rules_tread", categoryId: "rules" },
  { id: "fcd_q_rules_lights_on", categoryId: "rules" },
  { id: "fcd_q_rules_cellphone", categoryId: "rules" },
  { id: "fcd_q_rules_ped_collision", categoryId: "rules" },
  { id: "fcd_q_rules_emergency_vehicle", categoryId: "rules" },
  { id: "fcd_q_rules_freeway_stop", categoryId: "rules" },
  { id: "fcd_q_rules_learner_freeway", categoryId: "rules" },
  { id: "fcd_q_rules_unattended", categoryId: "rules" },
  { id: "fcd_q_int_4way_order", categoryId: "intersections" },
  { id: "fcd_q_int_4way_same_time", categoryId: "intersections" },
  { id: "fcd_q_int_mini_circle", categoryId: "intersections" },
  { id: "fcd_q_int_robot_dead", categoryId: "intersections" },
  { id: "fcd_q_int_turn_right", categoryId: "intersections" },
  { id: "fcd_q_int_green_arrow", categoryId: "intersections" },
  { id: "fcd_q_int_t_junction", categoryId: "intersections" },
  { id: "fcd_q_int_emergency_intersection", categoryId: "intersections" },
  { id: "fcd_q_int_ped_crossing", categoryId: "intersections" },
  { id: "fcd_q_int_blocked", categoryId: "intersections" },
  { id: "fcd_q_park_crossing", categoryId: "parking" },
  { id: "fcd_q_park_intersection", categoryId: "parking" },
  { id: "fcd_q_park_facing", categoryId: "parking" },
  { id: "fcd_q_park_bay", categoryId: "parking" },
  { id: "fcd_q_park_incline_down", categoryId: "parking" },
  { id: "fcd_q_park_incline_up", categoryId: "parking" },
  { id: "fcd_q_park_no_stopping", categoryId: "parking" },
  { id: "fcd_q_park_disabled", categoryId: "parking" },
  { id: "fcd_q_fd_two_second", categoryId: "following_distance" },
  { id: "fcd_q_fd_measure", categoryId: "following_distance" },
  { id: "fcd_q_fd_wet", categoryId: "following_distance" },
  { id: "fcd_q_fd_truck", categoryId: "following_distance" },
  { id: "fcd_q_fd_tailgated", categoryId: "following_distance" },
  { id: "fcd_q_fd_braking", categoryId: "following_distance" },
  { id: "fcd_q_fd_thinking", categoryId: "following_distance" },
  { id: "fcd_q_fd_night", categoryId: "following_distance" },
  { id: "fcd_q_fd_downhill", categoryId: "following_distance" },
  { id: "fcd_q_haz_scan", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_children", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_fatigue", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_blind_spot", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_aquaplane", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_ball", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_skid", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_animal_night", categoryId: "hazard_awareness" },
  { id: "fcd_q_haz_brake_fail", categoryId: "hazard_awareness" },
  { id: "fcd_vq_mc_front_brake", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_front_brake_turn", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_clutch_moveoff", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_gear_pattern", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_prohibition_sign", categoryId: "signs", codes: ["A1","A"] },
  { id: "fcd_vq_mc_class_speed_sign", categoryId: "signs", codes: ["A1","A"] },
  { id: "fcd_vq_mc_helmet", categoryId: "rules", codes: ["A1","A"] },
  { id: "fcd_vq_mc_a1_capacity", categoryId: "rules", codes: ["A1"] },
  { id: "fcd_vq_mc_pillion", categoryId: "rules", codes: ["A1","A"] },
  { id: "fcd_vq_mc_surface_hazards", categoryId: "hazard_awareness", codes: ["A1","A"] },
  { id: "fcd_vq_mc_truck_turbulence", categoryId: "hazard_awareness", codes: ["A1","A"] },
  { id: "fcd_vq_mc_following_distance", categoryId: "following_distance", codes: ["A1","A"] },
  { id: "fcd_vq_mc_incline_start", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_emergency_stop", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_slow_ride", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_swerve", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_mc_parking", categoryId: "parking", codes: ["A1","A"] },
  { id: "fcd_vq_mc_four_way_stop", categoryId: "intersections", codes: ["A1","A"] },
  { id: "fcd_vq_mc_lane_filtering", categoryId: "rules", codes: ["A1","A"] },
  { id: "fcd_vq_mc_kill_switch", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vq_hv_air_pressure", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vq_hv_spring_brake", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vq_hv_emergency_line", categoryId: "controls", codes: ["14"] },
  { id: "fcd_vq_hv_service_line", categoryId: "controls", codes: ["14"] },
  { id: "fcd_vq_hv_fifth_wheel_check", categoryId: "controls", codes: ["14"] },
  { id: "fcd_vq_hv_tug_test", categoryId: "controls", codes: ["14"] },
  { id: "fcd_vq_hv_landing_gear", categoryId: "controls", codes: ["14"] },
  { id: "fcd_vq_hv_diff_lock", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vq_hv_diff_lock_turn", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vq_hv_retarder", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vq_hv_jackknife", categoryId: "hazard_awareness", codes: ["14"] },
  { id: "fcd_vq_hv_stopping_distance", categoryId: "hazard_awareness", codes: ["10","14"] },
  { id: "fcd_vq_hv_following_distance", categoryId: "following_distance", codes: ["10","14"] },
  { id: "fcd_vq_hv_mass_sign", categoryId: "signs", codes: ["10","14"] },
  { id: "fcd_vq_hv_height_sign", categoryId: "signs", codes: ["10","14"] },
  { id: "fcd_vq_hv_definition", categoryId: "signs", codes: ["10","14"] },
  { id: "fcd_vq_hv_code14_gcm", categoryId: "rules", codes: ["14"] },
  { id: "fcd_vq_hv_prdp", categoryId: "rules", codes: ["10","14"] },
  { id: "fcd_vq_hv_air_tank_water", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vq_hv_wide_turn", categoryId: "intersections", codes: ["10","14"] },
  { id: "fcd_q2_sign_temp_yellow", categoryId: "signs" },
  { id: "fcd_q2_sign_guidance_green", categoryId: "signs" },
  { id: "fcd_q2_sign_brown_tourism", categoryId: "signs" },
  { id: "fcd_q2_sign_warn_tjunction", categoryId: "signs" },
  { id: "fcd_q2_sign_slippery", categoryId: "signs" },
  { id: "fcd_q2_sign_road_narrows", categoryId: "signs" },
  { id: "fcd_q2_sign_two_way", categoryId: "signs" },
  { id: "fcd_q2_sign_gravel_begins", categoryId: "signs" },
  { id: "fcd_q2_sign_wild_animals", categoryId: "signs" },
  { id: "fcd_q2_sign_command_blue", categoryId: "signs" },
  { id: "fcd_q2_sign_painted_island", categoryId: "signs" },
  { id: "fcd_q2_sign_lane_arrows", categoryId: "signs" },
  { id: "fcd_q2_sign_bus_lane", categoryId: "signs" },
  { id: "fcd_q2_sign_school_patrol", categoryId: "signs" },
  { id: "fcd_q2_sign_rumble_strips", categoryId: "signs" },
  { id: "fcd_q2_sign_clearance", categoryId: "signs" },
  { id: "fcd_q2_sign_officer_overrides", categoryId: "signs" },
  { id: "fcd_q2_sign_ped_blocks", categoryId: "signs" },
  { id: "fcd_q2_sign_speed_hump", categoryId: "signs" },
  { id: "fcd_q2_rules_accident_duty", categoryId: "rules" },
  { id: "fcd_q2_rules_tow_rope_speed", categoryId: "rules" },
  { id: "fcd_q2_rules_tow_gap", categoryId: "rules" },
  { id: "fcd_q2_rules_caravan_people", categoryId: "rules" },
  { id: "fcd_q2_rules_load_rear", categoryId: "rules" },
  { id: "fcd_q2_rules_door_open", categoryId: "rules" },
  { id: "fcd_q2_rules_reversing", categoryId: "rules" },
  { id: "fcd_q2_rules_coasting", categoryId: "rules" },
  { id: "fcd_q2_rules_hooter", categoryId: "rules" },
  { id: "fcd_q2_rules_night_parked_lights", categoryId: "rules" },
  { id: "fcd_q2_rules_cyclist_gap", categoryId: "rules" },
  { id: "fcd_q2_rules_ped_freeway", categoryId: "rules" },
  { id: "fcd_q2_rules_beam_reach", categoryId: "rules" },
  { id: "fcd_q2_rules_livestock", categoryId: "rules" },
  { id: "fcd_q2_rules_throwing", categoryId: "rules" },
  { id: "fcd_q2_rules_licence_carry", categoryId: "rules" },
  { id: "fcd_q2_rules_prof_alcohol", categoryId: "rules" },
  { id: "fcd_q2_rules_learner_ages", categoryId: "rules" },
  { id: "fcd_q2_rules_learner_validity", categoryId: "rules" },
  { id: "fcd_q2_ctrl_hazards", categoryId: "controls" },
  { id: "fcd_q2_ctrl_wipers_demister", categoryId: "controls" },
  { id: "fcd_q2_ctrl_oil_light", categoryId: "controls" },
  { id: "fcd_q2_ctrl_battery_light", categoryId: "controls" },
  { id: "fcd_q2_ctrl_seat_setup", categoryId: "controls" },
  { id: "fcd_q2_ctrl_headrest", categoryId: "controls" },
  { id: "fcd_q2_ctrl_ignition_moving", categoryId: "controls" },
  { id: "fcd_q2_ctrl_dry_steering", categoryId: "controls" },
  { id: "fcd_q2_int_uncontrolled", categoryId: "intersections" },
  { id: "fcd_q2_int_left_position", categoryId: "intersections" },
  { id: "fcd_q2_int_multilane_circle", categoryId: "intersections" },
  { id: "fcd_q2_int_green_ped_still", categoryId: "intersections" },
  { id: "fcd_q2_int_red_arrow", categoryId: "intersections" },
  { id: "fcd_q2_int_rail_multi_track", categoryId: "intersections" },
  { id: "fcd_q2_int_slipway", categoryId: "intersections" },
  { id: "fcd_q2_park_narrow_road", categoryId: "parking" },
  { id: "fcd_q2_park_direction", categoryId: "parking" },
  { id: "fcd_q2_park_kerb_gap", categoryId: "parking" },
  { id: "fcd_q2_park_bus_stop", categoryId: "parking" },
  { id: "fcd_q2_park_double", categoryId: "parking" },
  { id: "fcd_q2_park_unattended_check", categoryId: "parking" },
  { id: "fcd_q2_fd_three_second", categoryId: "following_distance" },
  { id: "fcd_q2_fd_stopped_hill", categoryId: "following_distance" },
  { id: "fcd_q2_fd_gravel", categoryId: "following_distance" },
  { id: "fcd_q2_haz_night_rural", categoryId: "hazard_awareness" },
  { id: "fcd_q2_haz_pothole", categoryId: "hazard_awareness" },
  { id: "fcd_q2_haz_fog_bank", categoryId: "hazard_awareness" },
  { id: "fcd_q2_haz_blowout", categoryId: "hazard_awareness" },
  { id: "fcd_q2_haz_oncoming_overtaker", categoryId: "hazard_awareness" },
  { id: "fcd_q2_car_child_restraint", categoryId: "rules", codes: ["8"] },
  { id: "fcd_q2_car_auto_feet", categoryId: "controls", codes: ["8"] },
  { id: "fcd_q2_car_power_steering", categoryId: "controls", codes: ["8"] },
  { id: "fcd_q2_car_spare_kit", categoryId: "controls", codes: ["8"] },
  { id: "fcd_q2_mc_tyre_check", categoryId: "controls", codes: ["A"] },
  { id: "fcd_q2_mc_chain", categoryId: "controls", codes: ["A"] },
  { id: "fcd_q2_hv_descent_gear", categoryId: "controls", codes: ["14"] },
  { id: "fcd_q2_hv_moving_brake_test", categoryId: "controls", codes: ["14"] },
  { id: "fcd_q3_park_kerb_distance", categoryId: "parking" },
  { id: "fcd_q3_park_direction", categoryId: "parking" },
  { id: "fcd_q3_int_four_way", categoryId: "intersections" },
  { id: "fcd_q3_int_dead_robot", categoryId: "intersections" },
  { id: "fcd_q3_int_turn_right", categoryId: "intersections" },
  { id: "fcd_q3_int_blocked", categoryId: "intersections" },
  { id: "fcd_vx_mc_gravel_braking", categoryId: "controls", codes: ["A1","A"] },
  { id: "fcd_vx_hv_downhill_gear", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vx_hv_air_pressure", categoryId: "controls", codes: ["10","14"] },
  { id: "fcd_vx_hv_arrester_bed", categoryId: "signs", codes: ["10","14"] },
  { id: "fcd_q4_sign_grammar_red_ring", categoryId: "signs" },
  { id: "fcd_q4_sign_grammar_triangle", categoryId: "signs" },
  { id: "fcd_q4_sign_temporary", categoryId: "signs" },
  { id: "fcd_q4_sign_shapes_unique", categoryId: "signs" },
  { id: "fcd_q4_sign_proceed_direction", categoryId: "signs" },
  { id: "fcd_q4_sign_no_stopping_vs_parking", categoryId: "signs" },
  { id: "fcd_q4_sign_derestriction", categoryId: "signs" },
  { id: "fcd_q4_sign_flashing_red", categoryId: "signs" },
  { id: "fcd_q4_sign_green_arrow", categoryId: "signs" },
  { id: "fcd_q4_sign_speed_min", categoryId: "signs" },
  { id: "fcd_q4_sign_guidance_green", categoryId: "signs" },
  { id: "fcd_q4_sign_brown_tourism", categoryId: "signs" },
  { id: "fcd_q4_mark_stop_line", categoryId: "signs" },
  { id: "fcd_q4_mark_centre_broken", categoryId: "signs" },
  { id: "fcd_q4_mark_barrier_side", categoryId: "signs" },
  { id: "fcd_q4_mark_painted_island", categoryId: "signs" },
  { id: "fcd_q4_mark_yellow_edge", categoryId: "signs" },
  { id: "fcd_q4_mark_arrow_lane", categoryId: "signs" },
  { id: "fcd_q4_mark_ped_block", categoryId: "signs" },
  { id: "fcd_q6_mark_double_solid", categoryId: "signs" },
  { id: "fcd_q6_mark_cross_barrier_legal", categoryId: "signs" },
  { id: "fcd_q6_mark_white_edge", categoryId: "signs" },
  { id: "fcd_q6_mark_yellow_freeway_shoulder", categoryId: "signs" },
  { id: "fcd_q6_mark_studs_white", categoryId: "signs" },
  { id: "fcd_q6_mark_studs_red", categoryId: "signs" },
  { id: "fcd_q6_mark_box_junction", categoryId: "signs" },
  { id: "fcd_q6_mark_keep_clear", categoryId: "signs" },
  { id: "fcd_q6_mark_stop_line_setback", categoryId: "signs" },
  { id: "fcd_q6_mark_lane_reduction", categoryId: "signs" },
  { id: "fcd_q6_mark_chevron_barrier", categoryId: "signs" },
  { id: "fcd_q6_temp_yellow_force", categoryId: "signs" },
  { id: "fcd_q6_temp_why_yellow", categoryId: "signs" },
  { id: "fcd_q6_temp_flagperson", categoryId: "signs" },
  { id: "fcd_q6_temp_speed_zone", categoryId: "signs" },
  { id: "fcd_q6_temp_cones", categoryId: "signs" },
  { id: "fcd_q6_temp_detour", categoryId: "signs" },
  { id: "fcd_q6_temp_vs_permanent", categoryId: "signs" },
  { id: "fcd_q6_temp_workers_end", categoryId: "signs" },
  { id: "fcd_q6_mark_speed_hump", categoryId: "signs" },
  { id: "fcd_q6_mark_kerb_paint", categoryId: "signs" },
  { id: "fcd_q8_ctrl_two_parts", categoryId: "controls" },
  { id: "fcd_q8_ctrl_yard_manoeuvres", categoryId: "controls" },
  { id: "fcd_q8_ctrl_incline_rollback", categoryId: "controls" },
  { id: "fcd_q8_ctrl_yard_contact", categoryId: "controls" },
  { id: "fcd_q8_ctrl_alley_dock", categoryId: "controls" },
  { id: "fcd_q8_ctrl_moving_off_look", categoryId: "controls" },
  { id: "fcd_q8_ctrl_steering_method", categoryId: "controls" },
  { id: "fcd_q8_ctrl_wheel_recovery", categoryId: "controls" },
  { id: "fcd_q8_ctrl_hands_on", categoryId: "controls" },
  { id: "fcd_q8_ctrl_cockpit_order", categoryId: "controls" },
  { id: "fcd_q8_ctrl_pretrip_exterior", categoryId: "controls" },
  { id: "fcd_q8_ctrl_start_neutral", categoryId: "controls" },
  { id: "fcd_q8_ctrl_ride_clutch", categoryId: "controls" },
  { id: "fcd_qs2_curve_single", categoryId: "signs" },
  { id: "fcd_qs2_curve_series", categoryId: "signs" },
  { id: "fcd_qs2_hairpin", categoryId: "signs" },
  { id: "fcd_qs2_dip", categoryId: "signs" },
  { id: "fcd_qs2_uneven", categoryId: "signs" },
  { id: "fcd_qs2_two_way_resumes", categoryId: "signs" },
  { id: "fcd_qs2_slippery", categoryId: "signs" },
  { id: "fcd_qs2_falling_rocks", categoryId: "signs" },
  { id: "fcd_qs2_side_wind", categoryId: "signs" },
  { id: "fcd_qs2_causeway", categoryId: "signs" },
  { id: "fcd_qs2_loose_stones", categoryId: "signs" },
  { id: "fcd_qs2_farm_animals", categoryId: "signs" },
  { id: "fcd_qs2_cyclists_ahead", categoryId: "signs" },
  { id: "fcd_qs2_signals_ahead", categoryId: "signs" },
  { id: "fcd_qs2_yield_ahead", categoryId: "signs" },
  { id: "fcd_qs2_tunnel", categoryId: "signs" },
  { id: "fcd_qs2_height_limit", categoryId: "signs" },
  { id: "fcd_qs2_width_limit", categoryId: "signs" },
  { id: "fcd_qs2_length_limit", categoryId: "signs" },
  { id: "fcd_qs2_mass_limit", categoryId: "signs" },
  { id: "fcd_qs2_minimum_speed", categoryId: "signs" },
  { id: "fcd_qs2_keep_left", categoryId: "signs" },
  { id: "fcd_qs2_no_towing", categoryId: "signs" },
  { id: "fcd_qs2_no_pedestrians_sign", categoryId: "signs" },
  { id: "fcd_qs2_dangerous_goods_prohibited", categoryId: "signs" },
  { id: "fcd_qs2_compulsory_ahead", categoryId: "signs" },
  { id: "fcd_qs2_no_through_road", categoryId: "signs" },
  { id: "fcd_qs2_hospital_sign", categoryId: "signs" },
  { id: "fcd_qs2_rest_area", categoryId: "signs" },
  { id: "fcd_qs2_emergency_phone", categoryId: "signs" },
  { id: "fcd_qs2_route_marker_shape", categoryId: "signs" },
  { id: "fcd_qs2_blue_vs_red_circle", categoryId: "signs" },
  { id: "fcd_qs2_warning_vs_regulatory", categoryId: "signs" },
  { id: "fcd_qs2_sign_placement_distance", categoryId: "signs" },
  { id: "fcd_qs2_supplementary_plate", categoryId: "signs" },
  { id: "fcd_qs2_sign_conflict_officer", categoryId: "signs" },
  { id: "fcd_qs2_faded_sign", categoryId: "signs" },
  { id: "fcd_qs2_chevron_board", categoryId: "signs" },
  { id: "fcd_qs2_hazard_marker", categoryId: "signs" },
  { id: "fcd_qs2_delineator_posts", categoryId: "signs" },
  { id: "fcd_qs2_st_andrews_cross", categoryId: "signs" },
  { id: "fcd_qs2_crossing_flashing_red", categoryId: "signs" },
  { id: "fcd_qs2_freeway_ends", categoryId: "signs" },
  { id: "fcd_qs2_lane_control_x", categoryId: "signs" },
  { id: "fcd_qs2_climbing_lane", categoryId: "signs" },
  { id: "fcd_qs2_exit_number", categoryId: "signs" },
  { id: "fcd_qs2_distance_board", categoryId: "signs" },
  { id: "fcd_qs2_end_of_restriction", categoryId: "signs" },
  { id: "fcd_qs2_restriction_until_cancelled", categoryId: "signs" },
  { id: "fcd_qs2_speed_limit_is_maximum", categoryId: "signs" },
  { id: "fcd_qs4_green_vs_blue_boards", categoryId: "signs" },
  { id: "fcd_qs4_brown_tourism", categoryId: "signs" },
  { id: "fcd_qs4_advance_vs_junction", categoryId: "signs" },
  { id: "fcd_qs4_exit_countdown_markers", categoryId: "signs" },
  { id: "fcd_qs4_no_through_road_sign", categoryId: "signs" },
  { id: "fcd_qs4_priority_road_sign", categoryId: "signs" },
  { id: "fcd_qs4_info_centre", categoryId: "signs" },
  { id: "fcd_qs4_street_name_position", categoryId: "signs" },
  { id: "fcd_qs4_danger_plate_chevrons", categoryId: "signs" },
  { id: "fcd_qs4_overhead_marker", categoryId: "signs" },
  { id: "fcd_qs4_general_warning_plate", categoryId: "signs" },
  { id: "fcd_qs4_construction_vehicles", categoryId: "signs" },
  { id: "fcd_qs4_pedestrian_signal_meaning", categoryId: "signs" },
  { id: "fcd_qs4_bus_signal_bar", categoryId: "signs" },
  { id: "fcd_qs4_signal_out_of_order", categoryId: "signs" },
  { id: "fcd_qs4_lane_control_green_arrow", categoryId: "signs" },
  { id: "fcd_qs3_priority_road_crossroad", categoryId: "signs" },
  { id: "fcd_qs3_priority_crossroad_ahead", categoryId: "signs" },
  { id: "fcd_qs3_side_road_ahead", categoryId: "signs" },
  { id: "fcd_qs3_staggered_junctions", categoryId: "signs" },
  { id: "fcd_qs3_height_warning_vs_prohibition", categoryId: "signs" },
  { id: "fcd_qs3_triangle_vs_ring_general", categoryId: "signs" },
  { id: "fcd_qs3_narrow_structure", categoryId: "signs" },
  { id: "fcd_qs3_temp_width_twin", categoryId: "signs" },
  { id: "fcd_qs3_temp_soft_shoulder", categoryId: "signs" },
  { id: "fcd_qs3_temp_surface_step", categoryId: "signs" },
  { id: "fcd_qs3_temp_loose_stones", categoryId: "signs" },
  { id: "fcd_qs3_drift", categoryId: "signs" },
  { id: "fcd_qs3_reduced_visibility", categoryId: "signs" },
  { id: "fcd_qs3_jetty_river", categoryId: "signs" },
  { id: "fcd_qs3_agricultural_vehicles", categoryId: "signs" },
  { id: "fcd_qs3_reservation_meaning", categoryId: "signs" },
  { id: "fcd_qs3_parking_reservation", categoryId: "signs" },
  { id: "fcd_qs3_time_limited_parking", categoryId: "signs" },
  { id: "fcd_qs3_end_mass_restriction", categoryId: "signs" },
  { id: "fcd_qs3_end_lane_reservation", categoryId: "signs" },
  { id: "fcd_qs3_warning_shape_priority", categoryId: "signs" },
  { id: "fcd_qs3_yellow_temp_reason", categoryId: "signs" },
  { id: "fcd_qs3_warning_no_obligation", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-007-01-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-008-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-009-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-009-06-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-010-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-010-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-010-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-010-06-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-010-07-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-011-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-012-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-012-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-012-06-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-012-07-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-013-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-013-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-013-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-013-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-013-06-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-013-07-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-014-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-014-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-014-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-014-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-014-07-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-017-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-017-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-017-06-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-017-07-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-019-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-020-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-020-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-021-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-regulatory-021-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-027-01-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-027-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-027-06-name", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-01-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-06-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-028-07-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-029-01-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-029-02-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-030-01-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-030-03-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-030-04-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-030-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-031-05-meaning", categoryId: "signs" },
  { id: "fcd_gen-sign-warning-031-06-meaning", categoryId: "signs" },
];

export const SCENARIO_META: ScenarioMeta[] = [
  { id: "sc_circle", categoryId: "intersections", title: "The busy traffic circle" },
  { id: "sc_pedestrian", categoryId: "hazard_awareness", title: "Ball into the road" },
  { id: "sc_following", categoryId: "following_distance", title: "Rain on the highway" },
  { id: "sc_4way", categoryId: "intersections", title: "The crowded four-way stop" },
  { id: "sc_parking", categoryId: "parking", title: "Quick stop at the shops" },
  { id: "sc_overtake", categoryId: "rules", title: "Slow truck on a barrier line" },
  { id: "sc_robot_dead", categoryId: "intersections", title: "Load-shedding intersection" },
  { id: "sc_emergency", categoryId: "hazard_awareness", title: "Siren behind you" },
  { id: "sc_amber", categoryId: "intersections", title: "The light turns amber" },
  { id: "sc_school", categoryId: "hazard_awareness", title: "School's out" },
  { id: "sc_railway", categoryId: "hazard_awareness", title: "Boom at the crossing" },
  { id: "sc_lane_change", categoryId: "hazard_awareness", title: "Changing lanes on the freeway" },
  { id: "sc_steep_descent", categoryId: "following_distance", title: "Long mountain pass" },
  { id: "sc_yield_junction", categoryId: "intersections", title: "Yield onto the main road" },
  { id: "sc_fatigue", categoryId: "hazard_awareness", title: "The long night drive" },
  { id: "vs_mc_wet_manhole", categoryId: "hazard_awareness", title: "Wet manhole cover mid-corner", codes: ["A1","A"] },
  { id: "vs_mc_crosswind_trucks", categoryId: "hazard_awareness", title: "Crosswind gap between two trucks", codes: ["A1","A"] },
  { id: "vs_mc_incline_start", categoryId: "controls", title: "Incline start during the K53 test", codes: ["A1","A"] },
  { id: "vs_mc_no_passenger_seat", categoryId: "rules", title: "Friend wants a lift with no passenger seat", codes: ["A1","A"] },
  { id: "vs_hv_wide_turn", categoryId: "intersections", title: "Heavy vehicle turning wide at an intersection", codes: ["10","14"] },
  { id: "vs_hv_air_warning", categoryId: "controls", title: "Air pressure warning light before departure", codes: ["10","14"] },
  { id: "vs_hv_coupling_check", categoryId: "controls", title: "Coupling check before a long haul", codes: ["14"] },
  { id: "vs_hv_long_descent", categoryId: "hazard_awareness", title: "Long downhill gradient with a loaded truck", codes: ["10","14"] },
  { id: "vs_mc_truck_only_lane", categoryId: "signs", title: "Unfamiliar truck-only lane marking", codes: ["A1","A"] },
  { id: "vs_hv_following_rain", categoryId: "following_distance", title: "Following a heavy vehicle in light rain", codes: ["8","10","14"] },
  { id: "sc2_taxi_stop", categoryId: "hazard_awareness", title: "The taxi ahead slows" },
  { id: "sc2_oncoming_overtaker", categoryId: "hazard_awareness", title: "Head-on closing fast" },
  { id: "sc2_cyclist_pass", categoryId: "rules", title: "Cyclist on a narrow road" },
  { id: "sc2_blowout", categoryId: "hazard_awareness", title: "Bang at 110" },
  { id: "sc2_fog_patch", categoryId: "hazard_awareness", title: "Into the fog" },
  { id: "sc2_green_ped", categoryId: "intersections", title: "Green light, slow walker" },
  { id: "sc2_breakdown_freeway", categoryId: "rules", title: "Dead on the freeway" },
  { id: "sc2_uncontrolled_int", categoryId: "intersections", title: "No signs, no robots" },
  { id: "sc2_gravel_bend", categoryId: "hazard_awareness", title: "Gravel road, tightening bend" },
  { id: "sc2_car_lap_child", categoryId: "rules", title: "The short trip excuse", codes: ["8"] },
  { id: "sc2_car_cruise_rain", categoryId: "hazard_awareness", title: "Cruise control and the downpour", codes: ["8"] },
  { id: "sc2_mc_robot_paint", categoryId: "hazard_awareness", title: "Wet arrows at the robot", codes: ["A"] },
  { id: "sc2_mc_pillion_ask", categoryId: "rules", title: "\"Just take me down the road\"", codes: ["A"] },
  { id: "sc2_hv_low_bridge", categoryId: "rules", title: "The 4,2 m bridge", codes: ["14"] },
  { id: "sc2_hv_brake_fade", categoryId: "controls", title: "Fading brakes on the pass", codes: ["14"] },
  { id: "vxs_mc_wet_intersection", categoryId: "hazard_awareness", title: "Wet robot, painted arrows", codes: ["A1","A"] },
  { id: "vxs_hv_long_descent", categoryId: "controls", title: "The pass warns: trucks use low gear", codes: ["10","14"] },
  { id: "vxs_mc_taxi_blindspot", categoryId: "hazard_awareness", title: "Alongside the taxi", codes: ["A1","A"] },
  { id: "sc_park_downhill_nokerb", categoryId: "parking", title: "Downhill on a gravel verge" },
  { id: "sc_park_reverse_out_blocked", categoryId: "parking", title: "Boxed in by a panel van" },
  { id: "sc_park_disabled_bay", categoryId: "parking", title: "The empty disabled bay" },
  { id: "sc_park_loading_zone", categoryId: "parking", title: "The convenient loading zone" },
  { id: "sc_park_door_cyclist", categoryId: "parking", title: "Opening the door on a busy road" },
  { id: "sc_park_hidden_crest", categoryId: "parking", title: "A gap just over the rise" },
  { id: "sc_sign_temp_vs_permanent", categoryId: "signs", title: "Two speed limits, one road" },
  { id: "sc_sign_officer_vs_robot", categoryId: "signs", title: "Green light, raised hand" },
  { id: "sc_sign_obscured", categoryId: "signs", title: "The sign behind the branch" },
  { id: "sc_sign_subplate", categoryId: "signs", title: "The small print under the sign" },
  { id: "sc_sign_height_limit", categoryId: "signs", title: "Low bridge, loaded roof rack" },
  { id: "sc_sign_no_overtaking_slow", categoryId: "signs", title: "Stuck behind a slow truck" },
  { id: "sc_fd_tailgated_queue", categoryId: "following_distance", title: "Pressured from behind" },
  { id: "sc_fd_gap_filled", categoryId: "following_distance", title: "The gap that keeps disappearing" },
  { id: "sc_fd_cant_see_past_truck", categoryId: "following_distance", title: "A wall of truck" },
  { id: "sc_fd_night_unlit", categoryId: "following_distance", title: "Beyond the headlights" },
  { id: "sc_fd_queue_over_crest", categoryId: "following_distance", title: "Brake lights over the rise" },
  { id: "sc_fd_gravel_dust", categoryId: "following_distance", title: "Dust on the gravel road" },
  { id: "sc_fd_towing_trailer", categoryId: "following_distance", title: "First trip with the trailer" },
  { id: "sc_ctrl_stall_intersection", categoryId: "controls", title: "Stalled at the lights" },
  { id: "sc_ctrl_oil_light_remote", categoryId: "controls", title: "Red light, long way from town" },
  { id: "sc_ctrl_hill_start_close", categoryId: "controls", title: "Hill start with company" },
  { id: "sc_ctrl_steering_heavy", categoryId: "controls", title: "The wheel goes heavy" },
  { id: "sc_ctrl_mirror_knocked", categoryId: "controls", title: "Mirror out of position" },
  { id: "sc_ctrl_auto_long_red", categoryId: "controls", title: "Long red in an automatic" },
];

/**
 * Yard-test modules, as the locked licence-prep page needs them.
 *
 * That page lists every module even to a learner who hasn't paid — the names,
 * the difficulty, how long each takes — because the list IS the pitch. So the
 * labels ship, and the thing being sold does not: the steps (actual
 * instructions and tips) and commonFaults come from /api/content/pack.
 *
 * stepCount rides along because the teaser shows "6 steps" and a
 * practised-so-far progress bar, both of which need the denominator without
 * needing a single instruction.
 */
export interface ModuleMeta {
  id: string;
  name: string;
  summary: string;
  difficulty: Difficulty;
  estMinutes: number;
  stepCount: number;
  /** Omitted = car, matching DriverModule. */
  group?: "car" | "motorcycle" | "heavy";
}

export const MODULE_META: ModuleMeta[] = [
  { id: "parallel_parking", name: "Parallel parking", summary: "Reverse neatly into a kerbside bay between two markers without touching them.", difficulty: 2, estMinutes: 12, stepCount: 6  },
  { id: "alley_docking", name: "Alley docking", summary: "Reverse into a 90° bay (the 'garage') and then drive out, staying inside the lines.", difficulty: 3, estMinutes: 14, stepCount: 6  },
  { id: "three_point_turn", name: "Three-point turn", summary: "Turn the vehicle to face the opposite direction in a narrow road using forward-reverse-forward.", difficulty: 2, estMinutes: 10, stepCount: 6  },
  { id: "incline_start", name: "Hill / incline start", summary: "Pull away on an uphill slope without rolling back more than the allowed margin.", difficulty: 2, estMinutes: 8, stepCount: 5  },
  { id: "vehicle_inspection", name: "Pre-trip vehicle inspection", summary: "The K53 pre-drive checks you must point out before the test begins.", difficulty: 1, estMinutes: 7, stepCount: 5  },
  { id: "mirror_blindspot", name: "Mirror & blind-spot routine", summary: "The observation discipline examiners look for before every manoeuvre.", difficulty: 1, estMinutes: 6, stepCount: 5  },
  { id: "moving_off", name: "Moving off into traffic", summary: "Pull away safely from the kerb into the traffic stream, with full observation.", difficulty: 1, estMinutes: 6, stepCount: 5  },
  { id: "lane_change", name: "Lane change", summary: "Move one lane across cleanly using the mirror–signal–blind-spot–manoeuvre routine.", difficulty: 2, estMinutes: 6, stepCount: 4  },
  { id: "turn_left", name: "Turning left at an intersection", summary: "The K53 sequence for a controlled left turn, keeping close to the left.", difficulty: 2, estMinutes: 7, stepCount: 5  },
  { id: "turn_right", name: "Turning right at an intersection", summary: "Position, yield and complete a right turn into the correct side of the new road.", difficulty: 3, estMinutes: 8, stepCount: 5  },
  { id: "controlled_stop", name: "Stopping & securing the vehicle", summary: "Bring the car to a smooth, safe stop at the side of the road and secure it.", difficulty: 2, estMinutes: 6, stepCount: 5  },
  { id: "freeway", name: "Entering & leaving a freeway", summary: "Match speed and merge safely from an on-ramp, and exit calmly via the off-ramp.", difficulty: 3, estMinutes: 9, stepCount: 5  },
  { id: "emergency_stop", name: "Emergency (controlled) stop", summary: "Stop the vehicle as quickly and safely as possible in a straight line, under full control.", difficulty: 3, estMinutes: 5, stepCount: 4  },
  { id: "moto_inspection", name: "Pre-ride inspection", summary: "The checks to point out before the motorcycle test begins.", difficulty: 1, estMinutes: 6, stepCount: 5 , group: "motorcycle" },
  { id: "moto_moving_off", name: "Moving off & balance", summary: "Pull away smoothly and under full control, with the correct observation.", difficulty: 1, estMinutes: 6, stepCount: 5 , group: "motorcycle" },
  { id: "moto_slow_ride", name: "Slow ride & figure-of-eight", summary: "Hold a steady speed band through a slow, curved course without touching the lines or putting a foot down.", difficulty: 3, estMinutes: 12, stepCount: 5 , group: "motorcycle" },
  { id: "moto_incline_start", name: "Incline start (no roll-back)", summary: "Stop on a slope and move off without the motorcycle rolling backward.", difficulty: 3, estMinutes: 8, stepCount: 4 , group: "motorcycle" },
  { id: "moto_emergency_stop", name: "Emergency stop", summary: "Stop as quickly and safely as possible, in a straight line, using both brakes.", difficulty: 3, estMinutes: 6, stepCount: 4 , group: "motorcycle" },
  { id: "moto_uturn", name: "U-turn (within the lines)", summary: "Turn the motorcycle around inside a marked width without touching a line or putting a foot down.", difficulty: 3, estMinutes: 8, stepCount: 5 , group: "motorcycle" },
  { id: "moto_lane_change", name: "Lane change (observation sequence)", summary: "The full mirrors–signal–lifesaver sequence for changing lanes on a motorcycle.", difficulty: 2, estMinutes: 7, stepCount: 5 , group: "motorcycle" },
  { id: "moto_road_ride", name: "Road ride: the observation system", summary: "The riding rhythm the examiner scores on the road: scan, mirrors, position, space.", difficulty: 2, estMinutes: 10, stepCount: 5 , group: "motorcycle" },
  { id: "moto_stop_park", name: "Stopping & parking the bike", summary: "End every ride the way the test ends: controlled stop, secure park, stand and dismount.", difficulty: 1, estMinutes: 6, stepCount: 5 , group: "motorcycle" },
  { id: "moto_swerve", name: "Emergency swerve", summary: "Steer around a sudden obstacle at speed, then bring the bike to a controlled stop.", difficulty: 3, estMinutes: 7, stepCount: 4 , group: "motorcycle" },
  { id: "hv_inspection", name: "Pre-trip inspection", summary: "The heavy-vehicle walk-around and cab checks before driving.", difficulty: 2, estMinutes: 9, stepCount: 5 , group: "heavy" },
  { id: "hv_air_brake_check", name: "Air-brake system check", summary: "Confirm the air-brake system builds, holds and warns correctly before driving.", difficulty: 3, estMinutes: 8, stepCount: 4 , group: "heavy" },
  { id: "hv_coupling", name: "Coupling a trailer", summary: "Connect a semi-trailer to the truck-tractor and confirm it's safe before moving.", difficulty: 3, estMinutes: 12, stepCount: 5 , group: "heavy" },
  { id: "hv_uncoupling", name: "Uncoupling a trailer", summary: "Separate the trailer from the tractor safely, leaving it stable and secure.", difficulty: 2, estMinutes: 9, stepCount: 5 , group: "heavy" },
  { id: "hv_incline_start", name: "Incline start (heavy vehicle)", summary: "Move a heavy vehicle off uphill without rolling back, using the parking brake.", difficulty: 3, estMinutes: 8, stepCount: 4 , group: "heavy" },
  { id: "hv_straight_reverse", name: "Reverse in a straight line", summary: "Back a long vehicle down a marked lane using mirrors only, without touching the lines.", difficulty: 2, estMinutes: 9, stepCount: 5 , group: "heavy" },
  { id: "hv_alley_dock", name: "Alley docking (heavy vehicle)", summary: "Reverse into a side bay from a blind side, the way trucks meet loading docks.", difficulty: 3, estMinutes: 12, stepCount: 5 , group: "heavy" },
  { id: "hv_turn_in_road", name: "Turn in the road", summary: "Turn a heavy vehicle to face the opposite direction inside a limited space.", difficulty: 3, estMinutes: 10, stepCount: 5 , group: "heavy" },
  { id: "hv_wide_turns", name: "Left & right turns (long vehicle)", summary: "Take intersections without kerbing the trailer or inviting cars into your blind side.", difficulty: 3, estMinutes: 10, stepCount: 5 , group: "heavy" },
  { id: "hv_road_ride", name: "Road drive: gears, brakes & space", summary: "The on-road discipline examiners score in a heavy vehicle: gear planning, smooth air brakes and space management.", difficulty: 2, estMinutes: 10, stepCount: 5 , group: "heavy" },
];

/**
 * Fingerprint of the full content bank.
 *
 * The cache key for a synced pack. It ships in the bundle, so a client always
 * knows which version it *should* have and can tell that its cached copy is
 * stale — which is what stops a content sprint being invisible to everyone who
 * synced before it.
 */
export const CONTENT_VERSION = "51e50f8da4b7";
