import type { Question } from "@/types";

/**
 * Vehicle-code–specific question bank — motorcycle (A1, A) and heavy (10, 14),
 * plus a few car-only (8) items. Each is tagged with the codes it applies to so
 * the selectors only serve it to the relevant learners; untagged core questions
 * stay universal. Derived from official/authoritative SA sources (K53 practical
 * manuals, the National Road Traffic Act and the SARTSM) — original wording.
 * Items touching exact test figures should be checked against the current
 * printed K53 manual edition before being treated as exam-certain.
 */
export const VEHICLE_QUESTIONS: Question[] = [
  {
    id: "vq_mc_front_brake",
    categoryId: "controls",
    prompt: "On a motorcycle, which lever or pedal applies the front wheel brake?",
    options: [
      "The pedal under the right foot",
      "The lever in front of the right handlebar grip",
      "The lever in front of the left handlebar grip",
      "Twisting the right handlebar grip",
    ],
    correctIndex: 1,
    explanation:
      "The front brake lever sits on the right handlebar, squeezed with the right-hand fingers; it supplies most of a motorcycle's stopping power and is normally used together with the rear brake pedal.",
    difficulty: 1,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_front_brake_turn",
    categoryId: "controls",
    prompt: "Why are riders taught never to grab the front brake hard while the handlebars are turned sharply?",
    options: [
      "It can stall the engine",
      "It can cause the front wheel to lose grip and the motorcycle to fall",
      "It drains the battery",
      "It activates the kill switch",
    ],
    correctIndex: 1,
    explanation:
      "A hard front brake application while leaning or turning sharply overloads the front tyre's available grip, which can cause the front wheel to wash out from under the rider.",
    difficulty: 2,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_clutch_moveoff",
    categoryId: "controls",
    prompt: "Which control is used, together with the throttle, to move off smoothly from a standstill on a motorcycle?",
    options: ["The rear brake pedal", "The clutch lever", "The indicator switch", "The kill switch"],
    correctIndex: 1,
    explanation:
      "The clutch lever, operated with the left hand, is gradually released ('feathered') while the throttle is gently opened to move off without stalling or lurching.",
    difficulty: 1,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_gear_pattern",
    categoryId: "controls",
    prompt: "What is the gear-change pattern on a typical motorcycle foot lever?",
    options: [
      "All gears are reached by lifting the lever",
      "First gear is selected by pressing down; the rest are reached by lifting up",
      "Gears are selected by twisting the lever",
      "There is no fixed pattern",
    ],
    correctIndex: 1,
    explanation:
      "Most motorcycles use a 'one down, the rest up' pattern: press the lever down with the toe for 1st gear, then lift up through 2nd, 3rd and beyond.",
    difficulty: 2,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_prohibition_sign",
    categoryId: "signs",
    prompt: "A round sign with a red border showing a motorcycle silhouette and a diagonal red line means:",
    options: [
      "Motorcycles must keep left",
      "Motorcycles are prohibited beyond this point",
      "Motorcycle parking only",
      "Motorcycles must dim headlights",
    ],
    correctIndex: 1,
    explanation:
      "A red-circle prohibition sign with a vehicle symbol and a diagonal bar bans that class of vehicle from the road or section of road ahead.",
    difficulty: 1,
    scope: "learners",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_class_speed_sign",
    categoryId: "signs",
    prompt: "A regulatory sign showing a number on a motorcycle silhouette (e.g. a speed limit shown beneath a motorcycle symbol) tells you:",
    options: [
      "The speed limit applies only to motorcycles",
      "Motorcycles are banned at that speed",
      "All vehicles must travel at that speed",
      "It is a guidance sign with no legal force",
    ],
    correctIndex: 0,
    explanation:
      "A sub-plate or symbol restricting a regulatory sign's effect to a class of vehicle (here, motorcycles) means the stated rule applies only to that class, not to all traffic.",
    difficulty: 2,
    scope: "learners",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_helmet",
    categoryId: "rules",
    prompt: "Under South African law, what must every motorcycle rider and pillion passenger wear?",
    options: [
      "A reflective vest",
      "A protective helmet that is properly fastened",
      "Gloves at all times",
      "A high-visibility jacket",
    ],
    correctIndex: 1,
    explanation:
      "The National Road Traffic Act requires riders and pillion passengers on motorcycles to wear a protective helmet, properly fastened under the chin, while the vehicle is in motion.",
    difficulty: 1,
    scope: "learners",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_a1_capacity",
    categoryId: "rules",
    prompt: "A Code A1 licence (light motorcycle) authorises you to ride a motorcycle with an engine capacity of:",
    options: [
      "Any capacity, including sidecars",
      "Not exceeding 125 cc",
      "Exceeding 125 cc only",
      "Three or four wheels only",
    ],
    correctIndex: 1,
    explanation:
      "Code A1 covers light motorcycles with an engine displacement not exceeding 125 cc; a full Code A licence is required for larger-capacity motorcycles.",
    difficulty: 1,
    scope: "learners",
    codes: ["A1"],
  },
  {
    id: "vq_mc_pillion",
    categoryId: "rules",
    prompt: "May a motorcycle lawfully carry a pillion passenger if it was not designed with a passenger seat and footrests?",
    options: [
      "Yes, as long as the passenger holds on to the rider",
      "No — a pillion passenger may only be carried if the motorcycle is equipped with a proper seat and footrests for that passenger",
      "Yes, but only for short distances",
      "Yes, if the passenger is an adult",
    ],
    correctIndex: 1,
    explanation:
      "A motorcycle may only carry a pillion passenger where a seat and footrests are specifically fitted for that purpose; carrying a passenger without them is unlawful.",
    difficulty: 2,
    scope: "learners",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_surface_hazards",
    categoryId: "hazard_awareness",
    prompt: "Why should a motorcyclist be especially cautious of painted lane lines, manhole covers and diesel spills, particularly in the wet?",
    options: [
      "They make the engine overheat",
      "They can be far more slippery for two wheels than for four",
      "They are illegal to ride over",
      "They interfere with the speedometer",
    ],
    correctIndex: 1,
    explanation:
      "A motorcycle balances on two narrow contact patches, so any reduction in grip from painted markings, metal covers or fuel spills has a much greater effect on stability than it does for a four-wheeled vehicle.",
    difficulty: 2,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_truck_turbulence",
    categoryId: "hazard_awareness",
    prompt: "A motorcyclist approaching a gap between two large trucks travelling in opposite directions should expect:",
    options: [
      "No effect on the motorcycle",
      "A possible gust of turbulent air that can push the motorcycle sideways",
      "An automatic speed reduction",
      "A change in road surface colour",
    ],
    correctIndex: 1,
    explanation:
      "Large vehicles push a bow-wave of air ahead of them; passing between or alongside them can produce sudden turbulence that destabilises a lighter, narrower vehicle such as a motorcycle.",
    difficulty: 2,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_following_distance",
    categoryId: "following_distance",
    prompt: "Compared with a car, why is it often recommended that a motorcyclist keep an even greater following distance from the vehicle ahead?",
    options: [
      "Motorcycles cannot brake as hard as a car in a straight line",
      "A motorcycle's narrower profile and lighter weight make it harder for the rider ahead to see, and a longer gap gives more time and space to react to a sudden hazard or road-surface change",
      "It is a legal requirement that differs from cars",
      "Motorcycles have shorter brake-light visibility",
    ],
    correctIndex: 1,
    explanation:
      "Riders are taught to keep extra space because they are less visible to others, are more affected by surface hazards, and benefit from the extra reaction time and swerve space a bigger gap provides.",
    difficulty: 2,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_incline_start",
    categoryId: "controls",
    prompt: "During the K53 motorcycle yard test 'stopping on an incline and moving off without rolling back', which controls work together to prevent the motorcycle rolling backward as you move off?",
    options: [
      "The kill switch and horn",
      "The rear brake (held until the clutch bites and throttle is applied) and the clutch/throttle combination",
      "The indicator switch only",
      "The mirrors only",
    ],
    correctIndex: 1,
    explanation:
      "The rider holds the rear brake to keep the motorcycle stationary on the slope, then smoothly brings in the clutch and applies throttle, releasing the rear brake only once drive is taking effect, so the motorcycle does not roll back.",
    difficulty: 3,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_emergency_stop",
    categoryId: "controls",
    prompt: "In the K53 motorcycle test, what is checked immediately after the rider performs an emergency stop?",
    options: [
      "That the engine was switched off",
      "That both wheels remained in a straight line without skidding or the motorcycle rolling, and that the stop was completed within the marked distance",
      "That the indicator was cancelled",
      "That the horn was sounded",
    ],
    correctIndex: 1,
    explanation:
      "Examiners assess whether the rider applied both brakes effectively without locking a wheel or losing control, bringing the motorcycle to a controlled stop within the test's marked area.",
    difficulty: 3,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_slow_ride",
    categoryId: "controls",
    prompt: "What is the purpose of the 'turning speed judgement' (commonly nicknamed the slow/curve ride) section of the motorcycle yard test?",
    options: [
      "To test how fast the rider can accelerate",
      "To test the rider's ability to maintain a required speed band through a curve without touching the boundary lines",
      "To test parallel parking ability",
      "To test how the rider answers oral questions",
    ],
    correctIndex: 1,
    explanation:
      "The rider must ride through a marked, curved course staying within a set minimum and maximum speed, without touching the inner or outer boundary lines, demonstrating control at low speed in a turn.",
    difficulty: 3,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_swerve",
    categoryId: "controls",
    prompt: "What must a motorcycle rider do immediately before an emergency swerve in the K53 test?",
    options: [
      "Switch off the engine",
      "Maintain a steady approach speed and be ready to apply both brakes after clearing the obstacle",
      "Sound the horn continuously",
      "Stand up on the footpegs",
    ],
    correctIndex: 1,
    explanation:
      "The rider approaches at the set speed, swerves around the obstacle using smooth handlebar/body input, and is assessed on maintaining balance and control before bringing the motorcycle to a stop once clear.",
    difficulty: 3,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_parking",
    categoryId: "parking",
    prompt: "When parking a motorcycle in a designated motorcycle bay, the rider should primarily ensure:",
    options: [
      "The motorcycle is parked on its side",
      "The motorcycle is upright and stable on its stand, within the marked bay and not obstructing other vehicles or pedestrians",
      "The engine is left running",
      "The mirrors are folded outward",
    ],
    correctIndex: 1,
    explanation:
      "As with any vehicle, a motorcycle must be parked stably and entirely within a legal, marked space without creating an obstruction or hazard.",
    difficulty: 1,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_four_way_stop",
    categoryId: "intersections",
    prompt: "At a four-way stop, a motorcyclist arriving at the same time as a car to its right should:",
    options: [
      "Always go first because motorcycles are smaller",
      "Give way to the vehicle on the right, following the normal right-of-way rule",
      "Sound the horn and proceed",
      "Wait for a traffic officer's signal regardless of other vehicles",
    ],
    correctIndex: 1,
    explanation:
      "Right-of-way rules at uncontrolled or stop-controlled intersections apply equally to motorcycles and other vehicles: the vehicle arriving from the right normally has priority.",
    difficulty: 1,
    scope: "learners",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_lane_filtering",
    categoryId: "rules",
    prompt: "Lane filtering (riding a motorcycle between stationary or slow-moving lanes of traffic) in South Africa is:",
    options: [
      "Explicitly permitted everywhere",
      "Not provided for as a right under the National Road Traffic Act, and riders who do so remain liable if it causes a collision",
      "Compulsory in heavy traffic",
      "Only allowed on freeways",
    ],
    correctIndex: 1,
    explanation:
      "South African traffic law does not grant motorcyclists a specific right to filter between lanes; doing so carries legal and safety risk, and the rider is fully liable for any resulting incident.",
    difficulty: 3,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_mc_kill_switch",
    categoryId: "controls",
    prompt: "What is the primary purpose of the engine cut-off ('kill') switch on a motorcycle?",
    options: [
      "To indicate a turn",
      "To stop the engine quickly without removing the ignition key, e.g. in an emergency",
      "To activate the horn",
      "To engage the differential lock",
    ],
    correctIndex: 1,
    explanation:
      "The kill switch breaks the ignition circuit so the rider can stop the engine instantly with a thumb, without needing to reach for the key — useful in a fall or mechanical emergency.",
    difficulty: 1,
    scope: "drivers",
    codes: ["A1", "A"],
  },
  {
    id: "vq_hv_air_pressure",
    categoryId: "controls",
    prompt: "Before moving off in an air-braked heavy vehicle, the driver must wait for the engine to idle until:",
    options: [
      "The fuel gauge shows full",
      "The air pressure gauges reach the manufacturer's safe operating range",
      "The radio switches on automatically",
      "The headlights warm up",
    ],
    correctIndex: 1,
    explanation:
      "Air brakes rely on a build-up of compressed air in storage tanks; the vehicle must not be moved until the gauges show sufficient pressure for the brakes (and, if coupled, the trailer brakes) to function safely.",
    difficulty: 1,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_spring_brake",
    categoryId: "controls",
    prompt: "What happens to the spring (parking) brakes on a heavy vehicle if air pressure is lost completely?",
    options: [
      "They release fully",
      "They apply automatically, since the spring brake is designed to fail to the 'on' position without air",
      "They have no effect either way",
      "They only apply to the front axle",
    ],
    correctIndex: 1,
    explanation:
      "Spring brakes are held off by air pressure; if pressure drops too low or is lost, the springs apply the brakes automatically as a fail-safe, which is why a heavy vehicle should never be moved on low air pressure.",
    difficulty: 2,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_emergency_line",
    categoryId: "controls",
    prompt: "On an articulated combination, what colour is the trailer's emergency (supply) air line typically marked?",
    options: ["Yellow", "Red", "Green", "Blue"],
    correctIndex: 1,
    explanation:
      "The red glad-hand coupling is the emergency/supply line; it keeps the trailer's air tank charged and will trigger the trailer brakes automatically if disconnected or it fails.",
    difficulty: 2,
    scope: "drivers",
    codes: ["14"],
  },
  {
    id: "vq_hv_service_line",
    categoryId: "controls",
    prompt: "On an articulated combination, what colour is the trailer's service air line typically marked?",
    options: ["Red", "Yellow", "White", "Black"],
    correctIndex: 1,
    explanation:
      "The yellow glad-hand coupling is the service line, which carries the signal that applies the trailer's brakes whenever the driver presses the foot brake (treadle) valve.",
    difficulty: 2,
    scope: "drivers",
    codes: ["14"],
  },
  {
    id: "vq_hv_fifth_wheel_check",
    categoryId: "controls",
    prompt: "Before driving off with a coupled semi-trailer, the driver must confirm the fifth-wheel coupling by:",
    options: [
      "Listening to the radio for a warning tone",
      "Visually checking that the kingpin is locked in the jaws and the safety lock-pin is engaged",
      "Checking the trailer's number plate only",
      "Reversing at speed to test it",
    ],
    correctIndex: 1,
    explanation:
      "A visual check that the locking jaws have closed around the kingpin and that the safety lock-pin is in place is essential before moving — an unlocked coupling can separate the trailer from the tractor while underway.",
    difficulty: 2,
    scope: "drivers",
    codes: ["14"],
  },
  {
    id: "vq_hv_tug_test",
    categoryId: "controls",
    prompt: "What is a 'tug test' used for when coupling an articulated vehicle?",
    options: [
      "Testing tyre pressure",
      "Confirming the fifth-wheel coupling is locked by gently driving the tractor forward against the applied trailer brakes",
      "Testing the horn",
      "Checking fuel consumption",
    ],
    correctIndex: 1,
    explanation:
      "With the trailer brakes applied, the driver gently moves the tractor forward; if the coupling is properly locked, the tractor will not pull away from the trailer, confirming a secure connection.",
    difficulty: 3,
    scope: "drivers",
    codes: ["14"],
  },
  {
    id: "vq_hv_landing_gear",
    categoryId: "controls",
    prompt: "Before moving off, the trailer's landing gear (support legs) must be:",
    options: [
      "Left half-lowered for stability",
      "Fully raised and secured",
      "Removed completely",
      "Lowered only on tar roads",
    ],
    correctIndex: 1,
    explanation:
      "The landing gear supports the front of an uncoupled trailer; it must be wound fully up and secured before the combination moves, otherwise it can drag, catch on the road, or be damaged.",
    difficulty: 1,
    scope: "drivers",
    codes: ["14"],
  },
  {
    id: "vq_hv_diff_lock",
    categoryId: "controls",
    prompt: "What is the purpose of a differential lock on a heavy vehicle?",
    options: [
      "To increase top speed",
      "To force both wheels on a drive axle to turn at the same speed for extra traction on loose or slippery surfaces",
      "To reduce fuel consumption on freeways",
      "To assist with parallel parking",
    ],
    correctIndex: 1,
    explanation:
      "Locking the differential prevents one wheel from spinning freely while the other has no traction, helping the vehicle pull through mud, sand or a slippery surface; it should be disengaged again on firm, dry roads.",
    difficulty: 2,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_diff_lock_turn",
    categoryId: "controls",
    prompt: "Why should the differential lock be disengaged before a heavy vehicle turns on a hard, dry surface?",
    options: [
      "It has no effect on turning",
      "Locking the diff forces both wheels to turn at the same speed even though the outer wheel needs to travel further in a turn, causing driveline strain and tyre scrubbing",
      "It will overheat the engine",
      "It disables the brakes",
    ],
    correctIndex: 1,
    explanation:
      "In a turn the outer wheel must rotate faster than the inner wheel; a locked differential prevents this speed difference, straining the drivetrain and scrubbing the tyres on a high-grip surface.",
    difficulty: 3,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_retarder",
    categoryId: "controls",
    prompt: "What is the purpose of an exhaust brake or engine retarder on a heavy vehicle?",
    options: [
      "To increase acceleration",
      "To provide extra engine braking on long descents, reducing wear and the risk of brake fade in the service brakes",
      "To charge the air tanks faster",
      "To operate the indicators",
    ],
    correctIndex: 1,
    explanation:
      "A retarder/exhaust brake slows the vehicle using engine braking effects rather than the wheel brakes, which is especially valuable on long downhill gradients to prevent the service brakes overheating ('brake fade').",
    difficulty: 2,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_jackknife",
    categoryId: "hazard_awareness",
    prompt: "What is 'jack-knifing' and when is an articulated vehicle most at risk of it?",
    options: [
      "When the trailer overtakes the tractor in a straight line on a freeway",
      "When the trailer swings out of line with the tractor, most likely under heavy braking, especially on a slippery surface",
      "When the tractor's engine stalls at a robot",
      "When the load shifts forward only",
    ],
    correctIndex: 1,
    explanation:
      "Jack-knifing occurs when the trailer skids and folds against the tractor unit, typically triggered by harsh or locked-wheel braking, particularly when the road surface is wet, icy or otherwise slippery.",
    difficulty: 2,
    scope: "drivers",
    codes: ["14"],
  },
  {
    id: "vq_hv_stopping_distance",
    categoryId: "hazard_awareness",
    prompt: "Heavy vehicles generally need a much longer distance to stop than a car. The main reasons include:",
    options: [
      "Heavy vehicles have smaller tyres",
      "Greater mass and load, combined with weight transfer and (on articulated units) the dynamics between tractor and trailer",
      "Heavy vehicles always have weaker brakes fitted",
      "Heavy vehicles cannot use their brakes below 60 km/h",
    ],
    correctIndex: 1,
    explanation:
      "A heavy vehicle's far greater mass requires much more energy to dissipate to stop, and a loaded or coupled vehicle's weight transfer and tractor-trailer dynamics further increase the distance and skill needed to stop safely.",
    difficulty: 2,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_following_distance",
    categoryId: "following_distance",
    prompt: "Why should a heavy-vehicle driver allow an even longer following distance than recommended for a car?",
    options: [
      "Heavy vehicles have better brakes than cars",
      "Longer stopping distances and reduced visibility around the vehicle mean more space and time are needed to react safely",
      "It is only a courtesy, not a safety requirement",
      "Following distance does not apply to heavy vehicles",
    ],
    correctIndex: 1,
    explanation:
      "Because a heavy vehicle takes longer to stop and the driver has larger blind spots, a greater following distance provides the extra time and space needed to respond safely to traffic ahead.",
    difficulty: 2,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_mass_sign",
    categoryId: "signs",
    prompt: "A regulatory sign showing a truck silhouette with a maximum mass figure (e.g. in tonnes) means:",
    options: [
      "Trucks heavier than that mass may not use the road",
      "It is a guidance sign showing average truck weights",
      "It only applies to buses",
      "It shows the recommended tyre pressure",
    ],
    correctIndex: 0,
    explanation:
      "Mass-limit signs prohibit vehicles whose gross vehicle mass (GVM) exceeds the figure shown from using that road, bridge or route, typically to protect a structure or residential area.",
    difficulty: 2,
    scope: "learners",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_height_sign",
    categoryId: "signs",
    prompt: "A warning sign showing a truck symbol and a height figure on a low bridge or tunnel is alerting drivers to:",
    options: [
      "A weighbridge ahead",
      "The maximum vehicle height that can safely pass under the structure",
      "A speed limit for trucks",
      "A truck inspection point",
    ],
    correctIndex: 1,
    explanation:
      "Height-restriction signs warn that any vehicle taller than the stated clearance risks striking the overhead structure and must not proceed.",
    difficulty: 1,
    scope: "learners",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_definition",
    categoryId: "signs",
    prompt: "Heavy vehicles in South Africa are generally defined, for signing and regulatory purposes, as vehicles with a gross vehicle mass (GVM) exceeding:",
    options: ["1 000 kg", "3 500 kg", "10 000 kg", "16 000 kg"],
    correctIndex: 1,
    explanation:
      "The SARTSM signing rules for heavy vehicles apply to vehicles exceeding 3 500 kg GVM (or gross combination mass, for combinations), distinguishing them from light motor vehicles for sign and lane-restriction purposes.",
    difficulty: 2,
    scope: "learners",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_code14_gcm",
    categoryId: "rules",
    prompt: "A Code 14 (now Code EC) licence is required for an articulated combination where the gross combination mass (GCM) is:",
    options: [
      "Under 3 500 kg",
      "Between 3 500 kg and 16 000 kg",
      "Exceeding 16 000 kg",
      "Exactly 3 500 kg",
    ],
    correctIndex: 2,
    explanation:
      "Code EC (the modern equivalent of the old Code 14) covers heavy articulated combinations with a GCM exceeding 16 000 kg, such as full semi-trailer, superlink or tanker combinations.",
    difficulty: 2,
    scope: "learners",
    codes: ["14"],
  },
  {
    id: "vq_hv_prdp",
    categoryId: "rules",
    prompt: "What additional document, beyond a driving licence, is generally required to drive a heavy vehicle for reward (commercially)?",
    options: [
      "A boating licence",
      "A Professional Driving Permit (PrDP)",
      "A firearm competency certificate",
      "A pilot's licence",
    ],
    correctIndex: 1,
    explanation:
      "Drivers of heavy or public-transport vehicles used for reward must hold a valid Professional Driving Permit (PrDP) in addition to the correct vehicle licence code, obtained through medical and other checks.",
    difficulty: 1,
    scope: "learners",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_air_tank_water",
    categoryId: "controls",
    prompt: "During the heavy-vehicle pre-trip inspection, why must the driver check the air tanks for water?",
    options: [
      "Water improves brake performance",
      "Moisture condenses in air tanks and, if not drained, can freeze in cold weather or cause corrosion and reduced braking reliability",
      "It indicates a fuel leak",
      "It is only a cosmetic check",
    ],
    correctIndex: 1,
    explanation:
      "Compressed air contains moisture that condenses in the tanks; if not drained it can corrode components, freeze valves in cold conditions, or otherwise compromise the air brake system's reliability.",
    difficulty: 3,
    scope: "drivers",
    codes: ["10", "14"],
  },
  {
    id: "vq_hv_wide_turn",
    categoryId: "intersections",
    prompt: "When a heavy vehicle needs to make a wide turn at an intersection to avoid mounting the kerb, other drivers should:",
    options: [
      "Try to squeeze into the gap the truck appears to be leaving",
      "Be patient and not try to pass on the inside of the turn, since the rear of a long vehicle swings differently from the front",
      "Overtake on the outside immediately",
      "Sound their hooter to hurry the truck",
    ],
    correctIndex: 1,
    explanation:
      "A long or articulated vehicle's trailer or rear body can swing wide or cut in during a turn; other road users should hold back and never try to fill the gap on the inside, where they could be struck or trapped.",
    difficulty: 2,
    scope: "drivers",
    codes: ["10", "14"],
  },
];
