import type { Question, RoadSign, SignCategory } from "@/types";
import { SIGNS, hasVerifiedName } from "@/lib/content/signs";

/**
 * Questions derived mechanically from the road-sign catalogue.
 *
 * The hand-authored packs cover the signs a learner meets most often, but the
 * catalogue holds far more verified sign meanings than the packs ever quiz. The
 * signs section is also the binding constraint on how many *distinct* mock
 * exams we can build (the mock needs 28 signs questions per paper), so widening
 * this pool is what stops a committed learner meeting the same paper twice.
 *
 * Derived, not invented: every prompt, answer and distractor is text already in
 * the catalogue, which came out of the official manual via scripts/extract_signs.py.
 * Nothing here is generated by a model — a wrong sign meaning in a licence app
 * is a real-world harm, so the only safe generator is one that can't author
 * facts, just recombine verified ones.
 *
 * Two framings per sign keep the same fact from *feeling* like the same
 * question (see FORMS below). Distractors are drawn from the same sign category
 * so they stay plausibly confusable rather than trivially wrong. Both framings
 * show the sign, so paper building already treats them as one subject via the
 * shared image and won't put both in the same paper.
 */

/*
 * The catalogue is OCR-derived and uneven, so each field below is gated
 * separately — a sign with a clean meaning but a mangled auto-name can still
 * carry a meaning-based question. Roughly a quarter of the catalogue survives;
 * that is the intended outcome, not an accident.
 */

/**
 * Some catalogue meanings carry the manual's caption prefix ("Examples: the
 * lane on the left…"). The text after it is the real meaning, so strip rather
 * than discard.
 */
function cleanMeaning(s: RoadSign): string {
  return (s.meaning?.trim() ?? "").replace(/^examples?:\s*/i, "");
}

/**
 * Qualifier plates — the small signs mounted under a main sign — have meanings
 * that only make sense attached to something else ("Applies only to the
 * operator as indicated."). Standing alone in an option list they are neither a
 * credible answer nor a fair distractor.
 */
const QUALIFIER_FRAGMENT = /^(applies|or under|may not|note|in this case|and\b|but\b)/i;

/**
 * A mid-string " : " means the extractor ran a caption into the body text —
 * "Dual-carriage freeway begins : The following rules apply to all freeways
 * Hand signals are not allowed…". The result reads as a sign name welded to an
 * unrelated rule, which is incoherent as an answer however long it is.
 */
const RUN_ON_CAPTION = /\s:\s/;

function hasUsableMeaning(s: RoadSign): boolean {
  const m = cleanMeaning(s);
  return (
    m.length >= 25 &&
    !m.endsWith(":") && // truncated stub, e.g. "Stop line:"
    /[.!]$/.test(m) && // a complete sentence, not a cut-off fragment
    /^[A-Z]/.test(m) &&
    !QUALIFIER_FRAGMENT.test(m) &&
    !RUN_ON_CAPTION.test(m) &&
    // The answer we would actually show has to say something. A first sentence
    // like "Modal transfer." or "Priority road." restates the sign's name and
    // explains nothing, which makes "what does this mean?" circular.
    optionText(m).length >= 30
  );
}

/**
 * Naming a sign is only asked of signs whose name was hand-verified.
 *
 * The OCR-derived fallback names are captions, not names — the catalogue
 * contains "Or under certain conditions" four separate times, plus "Examples"
 * and "May not". Those are unusable as answers *and* as distractors, and no
 * heuristic separates them reliably from real names like "No parking". So the
 * gate is provenance, not shape: if a human wrote the name, it can be quizzed.
 */
function hasUsableName(s: RoadSign): boolean {
  return hasVerifiedName(s) && (s.name?.trim().length ?? 0) >= 3;
}

/**
 * Guidance signs (route numbers, destinations, river names) make up nearly half
 * the catalogue but test recall of place names rather than road rules, so they
 * are excluded wholesale rather than filtered.
 */
const QUIZZABLE_CATEGORIES: SignCategory[] = ["regulatory", "warning", "information", "marking"];

function isQuizzable(s: RoadSign): boolean {
  return QUIZZABLE_CATEGORIES.includes(s.category) && Boolean(s.image);
}

/** Stable string hash → PRNG seed, so distractors never change between renders. */
function seedOf(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Deterministic pick of `n` items, seeded by the question id. */
function pickSeeded<T>(pool: readonly T[], n: number, seed: number): T[] {
  const a = [...pool];
  let s = seed || 1;
  for (let i = a.length - 1; i > 0; i--) {
    // xorshift32 — small, deterministic, and good enough for choosing distractors.
    s ^= s << 13;
    s ^= s >>> 17;
    s ^= s << 5;
    s >>>= 0;
    const j = s % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a.slice(0, n);
}

/**
 * Trim a meaning down to something that fits an option list without becoming
 * uninformative.
 *
 * Takes whole sentences, and keeps taking them until there is enough substance
 * to answer with — a bare "Priority road." is the sign's name again, not its
 * meaning, and the sentence after it is usually the part that actually
 * explains. Stops as soon as it has enough, so options stay readable.
 */
function optionText(meaning: string): string {
  const sentences = meaning.match(/[^.!]+[.!]/g) ?? [meaning];
  let out = "";
  for (const s of sentences) {
    out = `${out} ${s.trim()}`.trim();
    if (out.length >= 30) break;
  }
  return out;
}

function shortMeaning(s: RoadSign): string {
  return optionText(cleanMeaning(s));
}

/**
 * Two meanings are interchangeable as distractors only if they read differently.
 * Sibling signs in the catalogue often share near-identical text (e.g. the four
 * stop-sign variants), and offering two options that mean the same thing makes a
 * question unanswerable rather than hard.
 */
function distinctEnough(a: string, b: string): boolean {
  const norm = (t: string) => t.toLowerCase().replace(/[^a-z0-9 ]/g, "").trim();
  const x = norm(a);
  const y = norm(b);
  if (x === y) return false;
  return !x.startsWith(y.slice(0, 40)) && !y.startsWith(x.slice(0, 40));
}

/** Choose `n` distractors from the same category whose text is distinct. */
function distractors(
  target: RoadSign,
  pool: RoadSign[],
  text: (s: RoadSign) => string,
  n: number,
  seed: number,
): string[] {
  const targetText = text(target);
  const candidates = pool.filter(
    (s) => s.id !== target.id && distinctEnough(text(s), targetText),
  );
  const out: string[] = [];
  for (const c of pickSeeded(candidates, candidates.length, seed)) {
    const t = text(c);
    if (out.every((o) => distinctEnough(o, t))) out.push(t);
    if (out.length === n) break;
  }
  return out;
}

/**
 * Difficulty comes from the task and the sign, not from how big its category is.
 *
 * Two things actually make one of these harder:
 *  - the form. Seeing the sign and picking its meaning is recognition; reading a
 *    meaning and recalling which sign it belongs to has no picture to lean on.
 *  - how common the sign is. The hand-verified set is the signs a learner meets
 *    on real roads; the rest of the catalogue is long-tail.
 *
 * This matters beyond labelling: a beginner's first session is sorted with
 * easyFirst(), so mis-grading these as hard would hide them exactly when a new
 * learner most needs approachable sign practice.
 */
function difficultyFor(sign: RoadSign, form: Form): 1 | 2 | 3 {
  if (form === "name") return 1; // image plus a familiar name
  return hasUsableName(sign) ? 1 : 2; // meaning: common sign vs long-tail one
}

const CATEGORY_LABEL: Record<SignCategory, string> = {
  regulatory: "regulatory sign",
  warning: "warning sign",
  information: "information sign",
  guidance: "guidance sign",
  marking: "road marking",
};

/**
 * The framings. The same underlying fact reaches the learner as a different
 * task each time, which is what makes a finite bank feel deep:
 *
 *  - `meaning` — sees the sign, picks what it means (recognition)
 *  - `name`    — sees the sign, names it (recall)
 *
 * A third framing — read a meaning, name the sign, with no image — was built
 * and then removed. It does not work against this catalogue: South African sign
 * names are descriptive, so a sign's catalogue *meaning* is close to a
 * definition of its *name*. Fifteen of the twenty it produced were answerable by
 * matching a word in the prompt to a word in an option, without knowing anything
 * about signs — the worst asked which sign means "Railway crossing." with
 * "Railway crossing" among the options. Worse, they were graded hardest, so a
 * learner would have aced the top difficulty band by reading rather than
 * knowing, skewing their readiness score.
 *
 * Reverse-lookup is a good exercise; it just has to be hand-authored, where the
 * prompt can describe a situation instead of reciting the name.
 */
type Form = "meaning" | "name";
const FORMS: Form[] = ["meaning", "name"];

function build(sign: RoadSign, form: Form, pool: RoadSign[]): Question | null {
  const id = `gen-sign-${sign.id}-${form}`;
  const seed = seedOf(id);
  const difficulty = difficultyFor(sign, form);
  const label = CATEGORY_LABEL[sign.category];

  if (form === "meaning") {
    if (!hasUsableMeaning(sign)) return null;
    const answer = shortMeaning(sign);
    const wrong = distractors(sign, pool.filter(hasUsableMeaning), shortMeaning, 3, seed);
    if (wrong.length < 3) return null;
    return {
      id,
      categoryId: "signs",
      prompt: "What does this road sign mean?",
      options: [answer, ...wrong],
      correctIndex: 0,
      // Only name the sign in the explanation when that name is trustworthy;
      // otherwise lead with the category so we never assert an OCR fragment.
      explanation: hasUsableName(sign)
        ? `${sign.name}: ${cleanMeaning(sign)}`
        : `This ${label}: ${cleanMeaning(sign)}`,
      difficulty,
      scope: "learners",
      image: sign.image,
    };
  }

  // name
  if (!hasUsableName(sign)) return null;
  const wrong = distractors(sign, pool.filter(hasUsableName), (s) => s.name, 3, seed);
  if (wrong.length < 3) return null;
  return {
    id,
    categoryId: "signs",
    prompt: "Which sign is this?",
    options: [sign.name, ...wrong],
    correctIndex: 0,
    explanation: `This is the ${label} "${sign.name}". ${cleanMeaning(sign)}`,
    difficulty,
    scope: "learners",
    image: sign.image,
  };
}

function generate(): Question[] {
  const quizzable = SIGNS.filter(isQuizzable);
  const byCategory = new Map<SignCategory, RoadSign[]>();
  for (const s of quizzable) {
    const list = byCategory.get(s.category) ?? [];
    list.push(s);
    byCategory.set(s.category, list);
  }

  const out: Question[] = [];
  for (const sign of quizzable) {
    const pool = byCategory.get(sign.category) ?? [];
    // Need at least four signs in a category to build a four-option question.
    if (pool.length < 4) continue;
    for (const form of FORMS) {
      const q = build(sign, form, pool);
      if (q) out.push(q);
    }
  }
  return out;
}

export const GENERATED_SIGN_QUESTIONS: Question[] = generate();
