import { describe, expect, it } from "vitest";
import { statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  SIGN_IMAGE_APPEARANCE,
  SIGN_IMAGE_DIMENSIONS,
} from "@/lib/content/signs-dimensions";
import rawCatalog from "@/lib/content/signs.catalog.json";
import { SIGNS } from "@/lib/content/signs";
import { describeAppearance } from "@/lib/content/sign-traits";

/**
 * signs-dimensions.ts is GENERATED by scripts/gen-sign-dimensions.mjs.
 *
 * Its whole reason for existing is bundle weight: study routes need two tiny
 * per-sign facts (crop size, alt-text appearance) and importing either from
 * signs.ts dragged the full ~140KB catalogue into every one of their chunks.
 * These tests recompute BOTH projections from the live modules — the same
 * code the generator loads — so a catalogue change without a regeneration
 * fails CI here instead of shipping stale sizes or alt text.
 */

type Raw = { image?: string; w?: number; h?: number };

const expectedDims = new Map<string, { w: number; h: number }>();
for (const r of rawCatalog as Raw[]) {
  if (r.image && r.w && r.h) expectedDims.set(r.image, { w: r.w, h: r.h });
}
const actualDims = new Map(Object.entries(SIGN_IMAGE_DIMENSIONS));

/** The exact lookup the generator performs, recomputed live. */
const expectedAppearance = new Map<string, string>();
for (const sign of SIGNS) {
  if (!sign.image) continue;
  const appearance = describeAppearance(sign);
  if (appearance) expectedAppearance.set(sign.image, appearance);
}
const actualAppearance = new Map(Object.entries(SIGN_IMAGE_APPEARANCE));

describe("signs-dimensions matches the catalogue", () => {
  it("covers every crop in the catalogue", () => {
    const missing = [...expectedDims.keys()].filter((k) => !actualDims.has(k));
    expect(missing, "regenerate: node scripts/gen-sign-dimensions.mjs").toEqual([]);
  });

  it("contains nothing the catalogue doesn't have", () => {
    const extra = [...actualDims.keys()].filter((k) => !expectedDims.has(k));
    expect(extra).toEqual([]);
  });

  it("matches every width/height exactly", () => {
    for (const [image, dims] of expectedDims) {
      expect(actualDims.get(image), image).toEqual(dims);
    }
  });
});

describe("SIGN_IMAGE_APPEARANCE matches describeAppearance over SIGNS", () => {
  it("has exactly the confident appearances", () => {
    expect([...actualAppearance.keys()].sort()).toEqual([...expectedAppearance.keys()].sort());
    for (const [image, appearance] of expectedAppearance) {
      expect(actualAppearance.get(image), image).toBe(appearance);
    }
  });

  it("never leaks meaning into an appearance", () => {
    // The whole point of the alt-text design: describe WITHOUT answering.
    const byImage = new Map(SIGNS.filter((s) => s.image).map((s) => [s.image, s]));
    for (const [image, appearance] of actualAppearance) {
      const sign = byImage.get(image);
      if (!sign?.meaning) continue;
      // Any distinctive word of the meaning appearing verbatim in the
      // appearance would hand a screen-reader user the answer. Shape/colour
      // labels ("triangular and red") share no vocabulary with meanings by
      // construction; this pins that construction.
      for (const word of sign.meaning.split(/\s+/)) {
        if (word.length < 5) continue;
        expect(appearance.toLowerCase()).not.toContain(word.toLowerCase().replace(/[^a-z]/g, ""));
      }
    }
  });
});

describe("the projection stays worth its split", () => {
  it("is still a meaningful size win over the catalogue", () => {
    const dir = fileURLToPath(new URL("../src/lib/content", import.meta.url));
    const gen = statSync(`${dir}/signs-dimensions.ts`).size;
    const catalog = statSync(`${dir}/signs.catalog.json`).size;
    expect(gen).toBeLessThan(catalog / 2);
  });
});
